Libs/Core/ctkFileLogger.cpp

By default text files have \r\n ending on Windows and \n on Linux/Mac. The old implementation had \n end-of-line character hardcoded for all platforms.
On Windows, when trying to open a file (or copy-paste contents) that use \n as end-of-line character in a simple editor, such as Notepad, all the lines appear in one single line. This is very confusing for average users.
The fix uses the correct platform-specific end-of-line characters (\n or \r\n) instead of a hardcoded \n character.

ENH: Use platform-specific EOL character in log file

---

Applications/ctkXnatTreeBrowser/ctkXnatTreeBrowserMainWindow.cpp
Applications/ctkXnatTreeBrowser/ctkXnatTreeBrowserMainWindow.ui
Libs/XNAT/Core/ctkXnatAssessor.cpp
Libs/XNAT/Core/ctkXnatAssessor.h
Libs/XNAT/Core/ctkXnatAssessorFolder.cpp
Libs/XNAT/Core/ctkXnatAssessorFolder.h
Libs/XNAT/Core/ctkXnatDataModel.cpp
Libs/XNAT/Core/ctkXnatDataModel.h
Libs/XNAT/Core/ctkXnatExperiment.cpp
Libs/XNAT/Core/ctkXnatExperiment.h
Libs/XNAT/Core/ctkXnatFile.cpp
Libs/XNAT/Core/ctkXnatFile.h
Libs/XNAT/Core/ctkXnatObject.cpp
Libs/XNAT/Core/ctkXnatObject.h
Libs/XNAT/Core/ctkXnatProject.cpp
Libs/XNAT/Core/ctkXnatProject.h
Libs/XNAT/Core/ctkXnatReconstruction.cpp
Libs/XNAT/Core/ctkXnatReconstruction.h
Libs/XNAT/Core/ctkXnatReconstructionFolder.cpp
Libs/XNAT/Core/ctkXnatReconstructionFolder.h
Libs/XNAT/Core/ctkXnatResource.cpp
Libs/XNAT/Core/ctkXnatResource.h
Libs/XNAT/Core/ctkXnatScan.cpp
Libs/XNAT/Core/ctkXnatScan.h
Libs/XNAT/Core/ctkXnatScanFolder.cpp
Libs/XNAT/Core/ctkXnatScanFolder.h
Libs/XNAT/Core/ctkXnatSession.cpp
Libs/XNAT/Core/ctkXnatSession.h
Libs/XNAT/Core/ctkXnatSubject.cpp
Libs/XNAT/Core/ctkXnatSubject.h

Ivo refactored the download code of the XNAT API during the last hackfest.
A quick overview about the changes: The code for downloading was moved into the different xnatObjects similar to the fetch() function. Each xnat object has now its own implementation for downloading and the ctkXnatSession no longer has to provide specific implementations for the different object types.

Xnat download refactoring integration

---

CMake/ctkMacroBuildQtPlugin.cmake

If specified, the target(s) associated with designer, icon engine and
style plugins will be added into the specified folder when the project is
configured for an IDE supporting it.
For more details, see http://www.cmake.org/cmake/help/v2.8.9/cmake.html#prop_tgt:FOLDER

Add FOLDER parameter to ctkMacroBuildQtPlugin

---

Libs/DICOM/Widgets/ctkDICOMTableView.cpp

The reason was an unnecessary call of setUpTableView which performed the connection
to the signal/slots every time when invoked.

Fixed duplicate connection to Qt signal/slots in ctkDICOMTableView

---

Libs/DICOM/Widgets/ctkDICOMTableView.cpp

Cause of the bug:
If the dicom database is passed via the c'tor then the c'tor calls
setDicomDatabase, which calls setUpTableView, where the signals are
connected. Afterwards init is called by the c'tor, which also calls
setDicomDatabase, which then leads to the duplicate connection.
Solution:
The setUpTableview method is not really needed. All the connections can be
done in the init function, which is only called by the c'tor. Hence I removed the setUpTableview function.

Still possible duplicate signal connection in ctk dicom table view

---

Libs/Widgets/ctkConsole.cpp

Pressing Ctrl in the history area immediately jumped to the interactive area, essentially making Ctrl-C unavailable in the history area. Now we don't jump immediately to the interactive area if only a modifier key is pressed. This was the old behavior but factored out as part of the Python console simplification; but it has turned out it was actually necessary.

BUG: Enable Ctrl-C shortcut in Python console in the history area

---

Libs/Widgets/ctkLayoutFactory.cpp

This is particularly useful for custom layoutViewFactory setting the
widget visibility property to either true or false in a specialized
"ctkLayoutViewFactory::setupView" function. This commit will avoid
the widget visibility to be systematically forced to true by
"ctkLayoutManager::setupView".

Do not override widget visibility if already set in a layout view factory

---

CMake/ctkWrapPythonQt.py

Including QObject is sufficient, this was an oversight of the initial
implementation added in d3f81f4 (Move all PythonQt wrapping code into
one script. See #449)
Inspired-by: Eric Heim <e.heim@dkfz-heidelberg.de>

Do not require QWidget in decorator generated by ctkWrapPythonQt

---

Libs/XNAT/Core/Testing/ctkXnatSessionTest.cpp

The password for central.xnat.org for the ctk user, which is used within the ctkXnatSessionTest was expired, which lead to an immediate exception if executing the test.
i updated the password for the user

Update ctk user password for central.xnat.org, which was expired

---

Libs/Widgets/ctkColorPickerButton.cpp

Button icon has no color if setColor is called with invalid QColor.

Change icon for invalid color in ctkColorPickerButton

---

Libs/CommandLineModules/Core/ctkCmdLineModuleManager.h
Libs/PluginFramework/ctkPluginArchiveSQL_p.h

There are some build errors if you build CTK with the new Qt 5.5, which are related to some missing includes.
I was not able to use the BUILD_ALL configuration since both, ITK and VTK as well as Python did not work on my Mac OS X 10.10 with apple clang 6.1.0

Qt 5.5 fixes

---

Libs/Widgets/ctkColorPickerButton.cpp

Qt::BrushStyle cannot be used as an scoped enumeration

Fixed build error on Mac OS X

---

Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKDataSetArrayComboBoxTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKDataSetModelTest1.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDataSetArrayComboBox.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDataSetArrayComboBox.h
Libs/Visualization/VTK/Widgets/ctkVTKDataSetModel.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDataSetModel.h

1. ctkVTKDataSetArrayComboBox caused application crash when it is used for a VTK data set that is generated by a pipeline and the combobox was used for setting active scalar.
When a data set is changed due to a pipeline change, the data set is first reset and then recomputed. During reset the scalars are removed therefore the selection in the combobox is changed to item (-1), which triggers a data update. During update all the scalars are removed (again, so there is no change) but then the scalars are re-added when the data is recomputed. Qt combobox automatically selects the first item if an item is added, therefore the selection changes to the first active scalar. This change triggers a data set update, which starts with a reset. During reste the scalars are removed, therefore the …

BUG: Fixed ctkVTKDataSetArrayComboBox crashing and not updating

---

CMakeExternals/QtTesting.cmake

Since QtTesting development has been moved to Github, this commit
updates the URL accordingly.
The error occurred when using git protocol:
git clone https://paraview.org/QtTesting.git
Cloning into 'QtTesting'...
fatal: unable to access 'https://paraview.org/QtTesting.git/': Unknown SSL protocol error in connection to paraview.org:443
git clone https://paraview.org/QtTesting.git
Cloning into 'QtTesting'...
fatal: unable to access 'https://paraview.org/QtTesting.git/': SSL certificate problem: unable to get local issuer certificate
Reported-by: Sergey Aleshin <4memph@gmail.com>
Thanks: Sergey Aleshin <4memph@gmail.com>

QtTesting: Update Git repository URL to fix invalid cert issues.

---

Libs/Visualization/VTK/Core/CMakeLists.txt

For VTK < 6.3.0, vtkRenderingFreeTypeOpenGL is required by Visual Studio

Fix compilation on Visual Studio

---

CMakeExternals/PythonQt.cmake
Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp

This commit moves the call to PythonQt's cleanup function to be before the call that finalizes the Python interpreter. The interpreter should still be running during PythonQt::cleanup() so that calls to Py_DECREF succeed.
Applying this change exposes problems in PythonQt, so the following PythonQt PRs should be applied before this:
https://github.com/commontk/PythonQt/pull/25
https://github.com/commontk/PythonQt/pull/26

ctkAbstractPythonManager: Clean up PythonQt before finalizing the Python interpreter

---

CMakeExternals/PythonQt.cmake

Update PythonQt to commontk/PythonQt@cbf890f8eda122b8dca8e67d2bf75e85640ab297:
// -------------------------
commit cbf890f8eda122b8dca8e67d2bf75e85640ab297
Author: Max Smolens <max.smolens@kitware.com>
Date:   Tue Sep 15 15:45:30 2015 -0400
Fix PythonQtSignalReceiver crash during cleanup
This commit fixes a crash during PythonQt::cleanup(). While destroying the
PythonQtPrivate instance, any remaining PythonQtSignalReceivers that are kept
alive only by their parent object will be destroyed. The crash occurs when
PythonQtSignalReceiver's destructor calls back into
PythonQtPrivate::removeSignalEmitter() when the PythonQtPrivate instance is
mostly destroyed.
Includes test case that crashes without the fix.
// -------------------------

Update PythonQt to fix crash during PythonQt::cleanup()

---

CMake/ctkWrapPythonQt.py

This commit applies a patch similar to what was done in 09c2580. It basically
adds a workaround to avoid the warnings list below:
Warning	1	warning C4005: 'HAVE_FTIME' : macro redefinition	C:\D\N\Slicer-1-build\DCMTK-build\config\include\dcmtk\config\osconfig.h	175
Warning	2	warning C4005: 'HAVE_GETPID' : macro redefinition	C:\D\N\Slicer-1-build\DCMTK-build\config\include\dcmtk\config\osconfig.h	217
Warning	3	warning C4005: 'HAVE_IO_H' : macro redefinition	C:\D\N\Slicer-1-build\DCMTK-build\config\include\dcmtk\config\osconfig.h	274
Warning	4	warning C4005: 'HAVE_STRERROR' : macro redefinition	C:\D\N\Slicer-1-build\DCMTK-build\config\include\dcmtk\config\osconfig.h	622
Warning	5	warning C4005: 'HAVE_SYS_UTIME_H' : macro redefinition …

Workaround refined macro warning when building CTKDICOMWidgetsPythonQt

---

Libs/Visualization/VTK/Core/CMakeLists.txt

The test is run but only used to see if vtkRenderingFreeTypeFontConfig is
to be linked, but it is already tested whether the vtk target
vtkRenderingFreeTypeFontConfig actually exists.
In addition on Debian the FontConficConfig.cmake file doesn't extist, so the
test fails and linking as well, because the needed
vtkRenderingFreeTypeFontConfig is not added to the linker line.

Remove superfluous test on fontconfig

---

Libs/Scripting/Python/Widgets/Testing/Cpp/ctkPythonConsoleTest1.cpp
Libs/Widgets/ctkConsole.cpp
Libs/Widgets/ctkConsole.h
Libs/Widgets/ctkConsole_p.h

As of now, the user can add shortcuts to the console to trigger the
completion.
Default key (tab) is the same as before to preserve backward compatibility.

Add an option to the ctkConsole to add/set the completion shortcuts

---

Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.h

Add the export series, study, patient option to the right click menus.
Gets the files associated with a series and constructs
an export path based on the selected directory, using the patient
ID and name, study date and description, series number and
description.
The destination file is named sequentially, so a series will
be named 000000.dcm through to n-1.dcm.
Call the export series method for each selected study.
Call the export study for each selected patient.
Use a progress dialog to give the user feedback on the
status of the DICOM export.
Use message box pop ups to report errors to the user.
Fix a typo in a method name:
confirmDeleteSelectedIUDs -> confirmDeleteSelectedUIDs
Slicer Issue #3163

ENH: add the capability to export DICOM to disk

---

Libs/PluginFramework/ctkPluginFrameworkLauncher.cpp
Libs/PluginFramework/ctkPluginFrameworkLauncher.h

Previously one either had the choice of using the convenience run method,
without having the option of handling command line arguments, or handling
startup etc oneself. This change will add an additional parameter to the
convenience run method which takes the command line arguments and hands
them through.
cc: @saschazelzer

Extend the ctkPluginFrameworkLauncher convenience run method to accept cl args

---

Libs/Visualization/VTK/Widgets/ctkVTKCompositeFunction.cpp
Libs/Visualization/VTK/Widgets/ctkVTKPiecewiseFunction.cpp

In Qt 5.5:
Q_ASSERT will now expand the condition even in release mode when
asserts are disabled, albeit in an unreachable code path. This
solves compiler warnings about variables and functions that were
unused in release mode because they were only used in assertions.
Unfortunately, codebases that hid those functions and variables
via #ifndef will need to remove the conditionals to compile with
Qt 5.5.
http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.5.0

Support Qt 5.5 compilation

---

Libs/CommandLineModules/Core/Resources/ctkCmdLineModule.xsd

Add the pointfile element that has been added to the Slicer
execution module[1] by extending the fileType. Also separate
out the coordinateSystem attribute so that it can be used in both the point
and pointFile types.
[1] https://github.com/Slicer/SlicerExecutionModel/commit/608c7b06f9402b35f0ec01550a3b9e313582f683
Issue #622

BUG: Add pointfile element

---

Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMIndexer.h

Problem: When attempted to load DICOM files Slicer simply displayed that 0 patient was imported, without any hint of what could have been the problem.
Analysis: The issue was that study instance UID was missing from the DICOMDIR file but there was no error logged when this error occurred.
Solution: Added logging of DICOMDIR file parsing failures. Also added a bool return value to addDicomdir to allow the caller detect that error(s) occurred.

ENH: Added error logging to DICOMDIR file parsing

---

Libs/DICOM/Widgets/ctkDICOMTableManager.cpp
Libs/DICOM/Widgets/ctkDICOMTableManager.h

This commit simply adds a redirection of the 'double click' signal
from patients and studies table, as it exists for series.
On branch dicom-tablemanager-doubleclick
Changes to be committed:
modified:   Libs/DICOM/Widgets/ctkDICOMTableManager.cpp
modified:   Libs/DICOM/Widgets/ctkDICOMTableManager.h

Added double click support for patients and studies table

---

Libs/Core/CMakeLists.txt

The same functionality that is in linux's libdl is provided in FreeBSD's libc

fix Core linking: FreeBSD does not have a libdl

---

Libs/Widgets/CMakeLists.txt

fix alike that in other project: https://github.com/dotnet/coreclr/pull/550/files
fixes building CTKWidgets on FreeBSD 10

Add /usr/local/include for FreeBSD (QtOpengl)

---

Applications/ctkXnatTreeBrowser/ctkXnatTreeBrowserMainWindow.cpp
Applications/ctkXnatTreeBrowser/ctkXnatTreeBrowserMainWindow.h
Libs/XNAT/Core/ctkXnatSession.cpp
Libs/XNAT/Core/ctkXnatSession.h

Currently the CTK XNAT API does not notice when the XNAT session times out.
Accessing XNAT via the CTK XNAT API after a session timeout leads currently to a crash.
With this pullrequest we added the handling of session timeouts to the ctkXnatSession and also to the ctkXnatTreeBrowser application.

Xnat session timeout handling

---

Libs/Widgets/ctkCheckableComboBox.cpp

The method ctkCheckableComboBox::checkableModelHelper() is declared in
the header file but not implemented in the source file. This adds the
proper implementation.

ctkCheckableComboBox: implemented missing method checkableModelHelper()

---

Libs/Core/CMakeLists.txt

This commit generalizes the fix integrated in 9684161(fix Core
linking: FreeBSD does not have a libdl)

CTKCore: Generalize test checking if dl library is available.

---

Libs/XNAT/Core/ctkXnatDataModel.h
Libs/XNAT/Core/ctkXnatFile.cpp
Libs/XNAT/Core/ctkXnatObject.cpp
Libs/XNAT/Core/ctkXnatResource.cpp
Libs/XNAT/Core/ctkXnatScan.cpp

* Fixed misnamed named url parameter: "xsi:type" is wrong and may lead to query errors. Correct is "xsiType"
* Fixed a linker error that occurred on linux due to a missing export macro.
* Changed the way a ctkXnatScan is fetched by removing the ctkXnatResourceFolder from its hierarchy.
This prevents that a "Resource" folder is shown e.g. in the tree view between the scan and its resources

Xnat api fixes and improvements

---

Libs/XNAT/Core/ctkXnatSession.cpp
Libs/XNAT/Core/ctkXnatSession.h

This is sometimes necessary if the computer from which you want to connect to XNAT is behind a proxy.
Otherwise the connection to XNAT might not be possible.

Add possibility to set proxy for xnat

---

Libs/XNAT/Core/ctkXnatResource.cpp

error 422: Unprocessable entity
This can be reproduced with curl.
Omitting this query parameter solve the issue

Adding the xsiType=xnat:resource query parameter leads to an error when upload ing resources to XNAT

---

Libs/XNAT/Core/ctkXnatSession.cpp

The error was:
ctkXnatSessionPrivate::timeOutPeriod' :
only static const integral data members can be initialized within a class
Moved initialization to member initializer list.

Fixed build error for MSVS 2012

---

Libs/PluginFramework/ctkPluginFrameworkLauncher.cpp

* Removed d's property 'endSplashHandler' now useless
* use the QRunnable pointer received as parameter
* call the handler, if not null, at 'startup()' end

Fix for #602 - SplashScreen management

---

Libs/Widgets/ctkMaterialPropertyPreviewLabel.cpp
Libs/Widgets/ctkTransferFunctionBarsItem.cpp

On some platforms, e. g. Fedora armv7hl, CTK fails to build with the following errors:
~~~
[ 30%] Building CXX object Libs/Widgets/CMakeFiles/CTKWidgets.dir/ctkMaterialPropertyPreviewLabel.cpp.o
cd /builddir/build/BUILD/CTK-bdc8caca0458759e1672a94ca2857595d40f17b0/build/Libs/Widgets && /usr/bin/c++   -DCTKWidgets_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_OPENGL_LIB -DQT_SQL_LIB -DQT_TEST_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -isystem /usr/include/QtOpenGL -isystem /usr/include/QtXmlPatterns -isystem /usr/include/QtGui -isystem /usr/include/QtTest -isystem /usr/include/QtXml -isystem /usr/include/QtSql -isystem /usr/include/QtNetwork -isystem /usr/include/QtCore -I/builddir/build/BUILD/CTK-bdc8caca0458759e1672a94ca2857595d40f17b0/Libs/Widgets …

fix build on platforms where qreal is not equivalent of double

---

Libs/DICOM/Widgets/ctkDICOMBrowser.cpp

When removing patient/study/series from right
click, the table views in DICOM browser was not
updated.
Though the update is correctly done when using onRemoveAction, this is not the case with right click signal.

Update table views when deleting patient

---

Libs/Core/CMakeLists.txt
Libs/Core/Testing/Cpp/CMakeLists.txt
Libs/Core/Testing/Cpp/ctkCoreTestingMacrosTest.cpp
Libs/Core/Testing/Cpp/ctkCoreTestingUtilitiesTest.cpp
Libs/Core/ctkCoreTestingMacros.h
Libs/Core/ctkCoreTestingUtilities.cpp
Libs/Core/ctkCoreTestingUtilities.h
Libs/Core/ctkCoreTestingUtilities.tpp
Libs/Widgets/Testing/Cpp/ctkSettingsPanelTest1.cpp

Anticipating some bug fixes associated with the `ctkSettingsPanel`, I introduced `ctkCoreTestingMacros` and `ctkCoreTestingUtilities`
```
$ ctest -R Settings 
Test project /home/jcfr/Projects/CTK-build/CTK-build
Start 125: ctkSettingsDialogTest1
1/4 Test #125: ctkSettingsDialogTest1 ...........   Passed    0.25 sec
Start 126: ctkSettingsPanelTest
2/4 Test #126: ctkSettingsPanelTest .............   Passed    0.11 sec
Start 127: ctkSettingsPanelTest1
3/4 Test #127: ctkSettingsPanelTest1 ............   Passed    0.25 sec
Start 128: ctkSettingsTest1
4/4 Test #128: ctkSettingsTest1 .................   Passed    0.27 sec
100% tests passed, 0 tests failed out of 4
Label Time Summary:
CTKWidgets    =   0.88 sec (4 tests)
Total Test time (real) =   0.89 sec
```
```
$ ctest -R ctkCore
Test project …
```

Add ctk test utility

---

Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKHistogramTest2.cpp
Libs/Visualization/VTK/Widgets/ctkVTKHistogram.cpp
Libs/Visualization/VTK/Widgets/ctkVTKHistogram.h

Previously, the range was tied to the data array range. Now with the new
method, the user can change the range of the histogram easily.
When the range is changed, the histogram will be recomputed if the number
of bins changes.

Allow user to set/reset the range in ctkVTKHistogram

---

Libs/Core/ctkAbstractLibraryFactory.h
Libs/Core/ctkAbstractLibraryFactory.tpp

This does not seem to currently be exposed, and is important for controlling shared library symbol resolution behavior.
(See related comment at https://github.com/commontk/CTK/blob/b721b7caf80f994c1830b8b77d120bed5d47a865/Libs/PluginFramework/ctkPluginConstants.h#L98-L107)

RFC: LibraryFactory: allow setting LoadHints for symbol resolution

---

Libs/Visualization/VTK/Core/vtkLightBoxRendererManager.cpp

The order of how 2D actors are added to the renderer greatly influences the rendering result. Therefore, for consistent rendering results actor ordering in slice viewer has to be preserved when just changing the input image data.
Old behavior: When input to slice viewer was set to NULL (no image is selected for display), the image actor was removed from the renderer. When an image was selected again, the image actor was added again. This changed the actor order.
Implemented fix: Modified the behavior to only hide the image actor when input is set to NULL. This way when image input is later set to non-NULL, the image actor does not get promoted to the top of the actor list (but keeps its original position).
Fixes this problem in 3D Slicer: …

ENH: Preserve actor order in vtkLightBoxRendererManager

---

Libs/Widgets/Testing/Cpp/ctkLayoutManagerTest1.cpp
Libs/Widgets/ctkLayoutViewFactory.cpp

When multiple="true" specified in a view item then it means that all compatible views should be shown.
However, this only worked when cached views were enabled.
This caused in 3D Slicer "Tabbed slice" and "Tabbed 3D" layouts show only one view instead of all.

BUG: Fixed multiple view display in layouts

---

CMakeExternals/DCMTK.cmake

Suggested-by: Andriy Fedorov <fedorov@bwh.harvard.edu>
Tested-by: Christian Herz <christianherz1985@gmail.com>
$ git shortlog efe1a17..DCMTK-3.6.1_20161102 --no-merges
Jan Schlamelcher (11):
Fixed wrong usage of checkStringValue() in dcmpmap.
Several fixes for dcmpstat.
Fixed 32 vs. 64 bit problem in dcmqrdb.
Fixed using third party libraries with MinGW.
Fixed a problem with a previous commit.
Added OFvariant implementation for C++11.
Added API documentation for OFvariant etc.
Updated Makefile dependencies.
Updated man pages for new development snapshot.
Updated DCMTK_ABI_VERSION for new development snapshot.
Updated CHANGES.361 for new development snapshot.
Joerg Riesmeier (3):
Made clear that options +/-Uo require +Ug.
Output debug messages when updating attributes.
Added readXML mode …

ENH: Update to DCMTK-3.6.1_20161102

---

Libs/Widgets/ctkSettings.h

saveState and restoreState were not available from Python.

ENH: Improved python wrapping for ctkSettings

---

Libs/DICOM/Widgets/ctkDICOMThumbnailListWidget.cpp

This commit fixes the following warning:
/path/to/CTK/Libs/DICOM/Widgets/ctkDICOMThumbnailListWidget.cpp: In member function ‘void ctkDICOMThumbnailListWidgetPrivate::addSeriesThumbnails(const QModelIndex&)’:
/path/to/CTK/Libs/DICOM/Widgets/ctkDICOMThumbnailListWidget.cpp:149:15: warning: variable ‘studyIndex’ set but not used [-Wunused-but-set-variable]
QModelIndex studyIndex = index.parent();
^

DICOM/Widgets: Fix "unused-but-set-variable" warning

---

Libs/XNAT/Core/ctkXnatObject.cpp

This commit fixes the following warning:
```
/path/to/CTK/Libs/XNAT/Core/ctkXnatObject.cpp: At global scope:
/path/to/CTK/Libs/XNAT/Core/ctkXnatObject.cpp:432:51: warning: unused parameter ‘path’ [-Wunused-parameter]
void ctkXnatObject::fetchResources(const QString& path)
^
```

XNAT/Core: Fix unused warning in ctkXnatObject::fetchResources

---

Libs/Widgets/Testing/Cpp/ctkFittedTextBrowserTest1.cpp
Libs/Widgets/ctkFittedTextBrowser.cpp

Height of horizontal scrollbar is taken into account now.

BUG: Fixed ctkFittedTextBrowser height computation for wide content

---

Libs/Widgets/Testing/Cpp/ctkFlowLayoutTest1.cpp
Libs/Widgets/ctkFlowLayout.cpp

It allows variable sized items (so that they use the space optimally) and nice visual alignment at the same time (all rows have the same width).
See example below. Left: no justification. Right: with the new justification option enabled.

ENH: Implemented justified style for flow layout

---

Libs/Widgets/Testing/Cpp/ctkFittedTextBrowserTest1.cpp
Libs/Widgets/ctkFittedTextBrowser.cpp
Libs/Widgets/ctkFittedTextBrowser.h
Libs/Widgets/ctkFittedTextBrowser_p.h

ctkFittedTextBrowser uses available space efficiently to display text.
The widget can now further optimize use of available space by collapsing text.
If collapsible option is enabled then only a short teaser is shown (e.g., a one-line summary)
and the user has to click on "More..." to see the full text.

ENH: Made ctkFittedTextBrowser collapsible

---

Libs/Widgets/Testing/Cpp/ctkFittedTextBrowserTest1.cpp
Libs/Widgets/ctkFittedTextBrowser.cpp
Libs/Widgets/ctkFittedTextBrowser.h
Libs/Widgets/ctkFittedTextBrowser_p.h

setText methods were not virtual in base class, which made method calls from Python unpredictable.
Introduced new methods for setting collapsible text.
Also fixed const-correctness in ctkFittedTextBrowserPrivate class.

ENH: Improved ctkFittedTextBrowser API

---

Libs/DICOM/Core/Testing/Cpp/CMakeLists.txt
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest7.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp

More gracefully handle an error case that can
be anticipated.  Exception is not appropriate
when a meaningful return option is avaiable.
Closes #706

Don't through exception from ctkDICOMDatabase

---

Libs/Widgets/ctkFittedTextBrowser.cpp

Show ellipsis (...) where the collapsed text is cut.
Remove teaser separator(line break) character instead of replacing with space. This allows better control of what is displayed.
For example: "Some teaser<br>. This is more info." text expanded version was displayed as "Some teaser . This is more info.", but
now it is shown as "Some teaser. This is more info."

ENH: Improve ctkFittedTextBrowser collapsed text formatting

---

Libs/Core/Testing/Cpp/ctkCommandLineParserTest1.cpp
Libs/Core/ctkCommandLineParser.cpp

When a multi-value argument was passed to the command-line parser, all subsequent parameters were considered part of the argument.
This caused several test errors in Slicer: --ptyhon-script parameter was ignored if --additional-module-paths argument was specified before,
which made --python-script parameter ignored, and as a result, the provided Python script was not executed, which caused test failures
(py_nomainwindow_SlicerTestingExitFailureTest, py_nomainwindow_SlicerUnitTestWithErrorsTest, py_SlicerTestingExitFailureTest).
The root cause of the problem was that the check that compared a parameter to a known argument was incorrect: the parameter name
contained the prefix (--python-script) and this string was searched among argument names (such as python-script).
Fixed by parsing each …

BUG: Fixed multi-value argument parsing

---

CMake/ctkMacroCheckExternalProjectDependency.cmake

$ git shortlog 5ee3d50..0fff214 --no-merges
Jean-Christophe Fillion-Robin (1):
ExternalProjectDependency: Improve check for USES_TERMINAL support

Update ExternalProjectDependency based on commontk/Artichoke@0fff214

---

CMakeExternals/QtTesting.cmake
Libs/QtTesting/ctkXMLEventObserver.cpp
Libs/Visualization/VTK/Widgets/ctkVTKRenderViewEventPlayer.h
Libs/Visualization/VTK/Widgets/ctkVTKRenderViewEventTranslator.h
Libs/Widgets/ctkAxesWidgetEventPlayer.h
Libs/Widgets/ctkAxesWidgetEventTranslator.h
Libs/Widgets/ctkCheckableComboBoxEventPlayer.h
Libs/Widgets/ctkCheckableComboBoxEventTranslator.h
Libs/Widgets/ctkCheckableHeaderViewEventPlayer.h
Libs/Widgets/ctkCheckableHeaderViewEventTranslator.h
Libs/Widgets/ctkConsoleEventPlayer.h
Libs/Widgets/ctkConsoleEventTranslator.h
Libs/Widgets/ctkDoubleRangeSliderEventPlayer.h
Libs/Widgets/ctkDoubleRangeSliderEventTranslator.h
Libs/Widgets/ctkFileDialogEventPlayer.h
Libs/Widgets/ctkFileDialogEventTranslator.h
Libs/Widgets/ctkFontButtonEventPlayer.h
Libs/Widgets/ctkFontButtonEventTranslator.h
Libs/Widgets/ctkMatrixWidgetEventPlayer.h
Libs/Widgets/ctkMatrixWidgetEventTranslator.h
Libs/Widgets/ctkMenuComboBoxEventPlayer.h
Libs/Widgets/ctkMenuComboBoxEventTranslator.h
Libs/Widgets/ctkPathLineEditEventPlayer.h
Libs/Widgets/ctkPathLineEditEventTranslator.h
Libs/Widgets/ctkPopupWidgetEventPlayer.h
Libs/Widgets/ctkPopupWidgetEventTranslator.h
Libs/Widgets/ctkRangeSliderEventPlayer.h
Libs/Widgets/ctkRangeSliderEventTranslator.h
Libs/Widgets/ctkTreeComboBoxEventPlayer.h
Libs/Widgets/ctkTreeComboBoxEventTranslator.h

```
$ git shortlog 9951bc6..828b35e --no-merges
Ben Boeckel (1):
cmake: don't set the minimum version if not the top-level
Jean-Christophe Fillion-Robin (4):
test: Fix pq(Double)SpinBoxEventTranslatorTest
test: Fix pqEventRecorderTest
Fix -Woverloaded-virtual warning in custom event player
Fix -Woverloaded-virtual warning in custom event translator
Mathieu Westphal (2):
Enable use of continuous flush
Add feature to record interaction timings
Utkarsh Ayachit (1):
Fixes for Qt 5 / OsX test playback.
```

Update QtTesting to fix overload warnings

---

Libs/Core/ctkErrorLogFDMessageHandler.cpp

```
/path/to/CTK/Libs/Core/ctkErrorLogFDMessageHandler.cpp: In member function ‘void ctkFDHandler::setEnabled(bool)’:
/path/to/CTK/Libs/Core/ctkErrorLogFDMessageHandler.cpp:120:55: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
write(fileno(this->terminalOutputFile()), "\n", 1);
^
/path/to/CTK/Libs/Core/ctkErrorLogFDMessageHandler.cpp:136:83: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
write(fileno(this->terminalOutputFile()), qPrintable(newline), newline.size());
```

COMP: ctkErrorLogFDMessageHandler: Fix "unused-result" warning

---

CMake/ctkMacroSetupQt.cmake

Fixes #715
Suggested-by: Samuel John <github@samueljohn.de>

BUG: BuildSystem: Remove duplicated else in ctkMacroSetupQt.cmake

---

Libs/PluginFramework/ctkLDAPExpr.cpp

Bug that prevent to collect "objectclass" values because if the result of compare is 0, 0 is interpreted as "false". The result is that all fields value that does not correspond to objectclass are inserted. This is the inverse of what we want.

getMatchedObjectClasses does not collect class names

---

Libs/Visualization/VTK/Widgets/ctkVTKHistogram.cpp

When an image contained an (inf) value, it caused ctkVTKHistogram to crash because the computed bin index was out of bounds.

BUG: Fixed crash in histogram computation for inf image

---

Libs/Visualization/VTK/Core/vtkLightBoxRendererManager.cpp
Libs/Visualization/VTK/Widgets/ctkVTKSliceView.cpp

Default camera for overlay layer in ctkVTKSliceView was a default VTK camera with perspective projection.
This caused widgets appear tilted/warped when displayed near the edge of the render window.
This was particularly visible in vector text rendered by VTK seed widget (markup fiducials in 3D Slicer).
Before the fix:
After the fix:

BUG: Fixed warped widgets in ctkVTKSliceView overlay

---

CMake/ctkBlockCheckDependencies.cmake
SuperBuild.cmake

Pass CMAKE_CXX_STANDARD to sub-projects only when it is set. This fixes
errors like:
CMake Error at CMake/ctkMacroBuildLib.cmake:152 (add_library):
CXX_STANDARD is set to invalid value ''
Call Stack (most recent call first):
Libs/Core/CMakeLists.txt:136 (ctkMacroBuildLib)

BUG: Fix build when CMAKE_CXX_STANDARD is not set

---

README.rst

The CDash project for CTK seems retired. Clicking the test results link should
navigate to CircleCI. Additionally, update the build status icon to 'shield'
style, which includes the word 'circleci'.

STYLE: Fix CircleCI link

---

Libs/DICOM/Widgets/Resources/UI/ctkDICOMObjectListWidget.ui
Libs/DICOM/Widgets/ctkDICOMObjectListWidget.cpp
Libs/DICOM/Widgets/ctkDICOMObjectListWidget.h

Added "Copy metadata" button (next to "Copy path" button) in the DICOM metadata browser (ctkDICOMObjectListWidget) to copy all metadata to the clipboard.
It is useful for collecting information from users when they reporting DICOM loading errors.
Also added tooltip for the existing, very useful, but hard-to-discover feature: if user clicks on a tag then its definition is displayed at http://dicomlookup.com.

ENH: Added Copy metadata button to DICOM metadata widget

---

Libs/DICOM/Widgets/Resources/UI/ctkDICOMObjectListWidget.ui
Libs/DICOM/Widgets/ctkDICOMObjectListWidget.cpp
Libs/DICOM/Widgets/ctkDICOMObjectListWidget.h
Libs/DICOM/Widgets/ctkDICOMObjectModel.h

To further improve ability to collect DICOM metadata information from users, the following features were added to the DICOM metadata window:
- free-text search in tag, name, vale fields
- export of filtered results (useful for easily excluding patient identifiable information)
- exporting of tags in all files in the files list (useful for example for getting image position information that requires all values), it works combined with filtering
- expand/collapse of all branches
- show total number of files and 1-based file index
- resize column widths to content by default
GUI:
Example copy filtered metadata from all files in the series:
<pre>
images/1-270.dcm	[0020,0032]	ImagePositionPatient	[3] -225.000000, -225.000000, 55.500000	DS	34
images/10-268.dcm	[0020,0032]	ImagePositionPatient …

ENH: Added filtering and multi-file export to DICOM metadata dialog

---

Libs/Widgets/ctkConsole.cpp

1. Removed extra blank lines from Python console output. Fixes #731.
2. Fixed invalid command line when string is printed while editing command. For example, copy-paste the command below to the console (it prints a message after 3 and 6 seconds) then immediately enter "print" (without quotes, do not press Enter), wait for the message to appear, enter "123123123" (without quotes) to complete the command, and press Enter => now the command string is correct (before this fix it was corrupted).
def delayedprint():
print "something printed 1"
qt.QTimer.singleShot(3000, delayedprint)

BUG: Fixed Python console regressions

---

Libs/Widgets/ctkMessageBox.cpp

This commit ensures the text and checkbox are properly
displayed by using the API available in Qt >= 5.2

BUG: ctkMessageBox: Fix layout setting checkbox with Qt >= 5.2

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp

Testing DICOM import speed on Windows with Qt4, it turned out that excessive logging and progress updates slowed down the import by almost an order of magnitude.
Speed comparison example:
Baseline (without any changes):
"DICOM indexer has successfully processed 801 files [72.72s]"
After changing ctkDICOMIndexer to update progress report at every 10% increase (not at every processed file):
"DICOM indexer has successfully processed 801 files [37.53s]"
After cutting down on debug logs:
"DICOM indexer has successfully processed 801 files [11.46s]"

ENH: Improve DICOM import speed

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h

Problem (reported in #744):
Studies/Series only gets updated upon patient selection for the latest created ctkDICOMBrowser. When selecting another patient in an earlier instance, neither Studies nor Series list gets updated.
The following code reproduces the problem:
import ctk
dicomBrowser = ctk.ctkDICOMBrowser()
dicomBrowser.show()
dicomBrowser1 = ctk.ctkDICOMBrowser()
dicomBrowser1.show()
dicomBrowser2 = ctk.ctkDICOMBrowser()
dicomBrowser2.show()
Studies/series list only updates in dicomBrowser2, the two other instances are broken.
Solution:
Unless a connection name is specified, ctkDICOMDatabase always generates a unique connection name.

BUG: Fixed DICOM browser refresh issue when multiple browsers are created

---

Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest7.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp

When a dataset cannot be initialized, log an error
and return an empty string for consistency.
Also do not cache value (means that a future call may
succeed with correct value if data file becomes available)
Fixes #749

BUG: consistent return for value of uninitialized data

---

Libs/Widgets/ctkConsole.cpp

Erasing whitespace doesn't make very much sense for any language,
but especially not for python.
Fixes #751

BUG: preserve whitespace in console completion

---

Libs/Core/ctkCompilerDetections_p.h
Libs/Visualization/VTK/Core/ctkVTKScalarsToColorsUtils.cpp
Libs/Visualization/VTK/Core/vtkDiscretizableColorTransferChart.cpp
Libs/Visualization/VTK/Core/vtkDiscretizableColorTransferChart.h
Libs/Visualization/VTK/Core/vtkScalarsToColorsContextItem.cpp
Libs/Visualization/VTK/Core/vtkScalarsToColorsPreviewChart.cpp
Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKDiscretizableColorTransferWidget.ui
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsComboBoxTest1.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.h
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsComboBox.cpp

This PR updates the transfer widget integrated in https://github.com/commontk/CTK/pull/755 so that it can be used with C++ < 11. Waiting we change the default build type in Slicer, we still need to support it. It is a matter of weeks.

Update ctk vtk discretizable color transfer widget to support qvtk open gl widget

---

Libs/Widgets/ctkRangeWidget.h

@lassoan  @jcfr as discussed in https://github.com/Slicer/Slicer/pull/823, it will be nice to have the setRange method available in Python too (this avoid many crash when setting minimum and maximum which are greater/smaller than the current maximum/minimum of the widget).

ENH: add Q_INVOKABLE to ctkRangeWidget::SetRange

---

CMake/ctkExternalProjectAlwaysConfigure.cmake
SuperBuild.cmake

This commit improves the code forcing a reconfiguration and
rebuild of the main project. This is an attempt to fix rebuild issues
discussed at https://github.com/Slicer/Slicer/pull/823#issuecomment-341566829
It also removes STEP_TARGETS obsoleted by f73c517 (Update dashboard
driver script to submit a regular project layout.)

COMP: Ensure main project is always re-configured

---

Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.cpp

Hi @jcfr, may you kindly merge this?
This avoid crashes when the VolumeProperty is not set (analogous to the method moveAllPoints).

BUG: fixing crash for spreadAllPoints in ctkVTKVolumePropertyWidget

---

Libs/Visualization/VTK/Core/CMakeLists.txt
Libs/Visualization/VTK/Core/vtkScalarsToColorsContextItem.cpp
Libs/Visualization/VTK/Core/vtkScalarsToColorsContextItem.h
Libs/Visualization/VTK/Core/vtkScalarsToColorsHistogramChart.cpp
Libs/Visualization/VTK/Core/vtkScalarsToColorsHistogramChart.h
Libs/Visualization/VTK/Widgets/Testing/Cpp/CMakeLists.txt
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKDiscretizableColorTransferWidgetTest1.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.h
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsComboBox.cpp
Libs/Widgets/ctkRangeWidget.cpp

Improve the ctkVTKDiscretizableColorTransferWidget:
- Add options to set the histogram chart height
- Fix histogram conversion
- Replace clamp by qBound

Add options to handle color widget height

---

Libs/Core/ctkModelTester.cpp

Windows uses default long size of 32bit on 64bit systems, so casting a pointer to long fails with pedantic build options. This currently breaks MSYS2 build (MinGW based) but should likely cause problems on MSVC too.

ctkModelTester.cpp: long vs pointer have different size on MSYS2

---

Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp

This commit updates the method so that it also enables depth peeling for
volumes along with the translucent geometry. Only supported on OpenGL2
with dual-depth peeling.
Suggested-by: Ken Martin <ken.martin@kitware.com>

ENH: ctkVTKAbstractView: Update setUseDepthPeeling to also enable depth peel for volumes

---

Applications/ctkSimplePythonShell/Testing/Python/ctkWidgetsTest.py
Applications/ctkSimplePythonShell/Testing/Python/vtkPythonSmoke.py
Applications/ctkSimplePythonShell/Testing/Python/wrappedVTKQInvokableTest.py
Applications/ctkSimplePythonShell/Testing/Python/wrappedVTKSlotTest.py
CMake/ctkMacroWrapPythonQtModuleInit.cpp.in
CMake/ctk_compile_python_scripts.cmake.in
Libs/Scripting/Python/Core/Python/ctk/__init__.py.in
Libs/Scripting/Python/Core/Python/qt/__init__.py.in
Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp

Ifdef where necessary, use statements valid for python 3 and 2.6+ where
possible.

Add python3 support

---

Libs/Visualization/VTK/Widgets/ctkVTKChartView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKChartView.h
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.h

- Added function to set chart extent (i.e. axis range) in ctkVTKChartView and ctkVTKVolumePropertyWidget
- Removed unnecessary update call from ctkVTKScalarsToColorsView::onBoundsChanged. It caused a reset of extent, which is undesired when only the transfer function is being shifted. This should not cause issues as the bounds already cover the data range, so the extent can be set to whatever needed, and at the same time it does not override what the user set
- Added python compatibility functions to ctkVTKVolumePropertyWidget

ENH: Better chart bound and extent handling

---

CMake/ctkMacroBuildLibWrapper.cmake

Ensuring only the required symbols are visible will help speed up the
dynamic loader symbol lookup.
Indeed, here is a quote from [1]:
"When the dynamic loader searches for symbols, it performs string
comparisons with every symbol in the search scope. Reducing the number
of symbols the dynamic loader has to go through to find the desired
symbol improves your app’s performance"
[1] https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/DynamicLibraryUsageGuidelines.html#//apple_ref/doc/uid/TP40001928-SW22

PERF: Ensure PythonQt python module only have their init function visible.

---

Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsView.cpp

The setAxesToChartBounds call has recently been removed so that the chart extent is not reset when the transfer function bounds change. This prevented resetting the extent defined by the user when shifting the transfer function. However, if there was no valid extent defined, without this call the chart was not shown at all. By resetting the extent only if it was invalid solves both issues.

BUG: Re-add range reset on bounds change if range is invalid

---

CMake/ctkMacroCheckExternalProjectDependency.cmake

```
$ git shortlog 75af1d0..9c98004 --no-merges
Jean-Christophe Fillion-Robin (3):
ExternalProjectDependency: Ignore CACHE value of type INTERNAL
circleci: Use dockbuild/centos6 instead of unmaintained centosbuild/centos6
ExternalProjectDependency: If set, propagate CMAKE_JOB_* variables
```

ENH: Update ExternalProjectDependency system based on commontk/Artichoke@9c98004

---

Libs/Widgets/Testing/Cpp/ctkLayoutManagerTest1.cpp
Libs/Widgets/ctkLayoutManager.cpp
Libs/Widgets/ctkLayoutManager.h
Libs/Widgets/ctkLayoutViewFactory.cpp

- For layouts with splitter: added "splitSize" attribute to specify default item size.
- For layouts without splitter: added "horizontalStretch" and "verticalStretch" attributes to specify relative size of views.
Updated documentation and test accordingly.
This improvement is required for fixing https://issues.slicer.org/view.php?id=4530.

ENH: Allow layout manager to adjust view sizes

---

Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMIndexer.h

Import of a DICOM study partially failed because some of the folder names (that were generated from DICOM series description) started with . character. On Mac and Linux system, these folders were considered as hidden folders and were skipped from DICOM import because the DICOM indexer by default ignored hidden folders.
The problem is fixed by adding includeHidden argument (enabled by default) to ctkDICOMIndexer::addDirectory.

BUG: Allow DICOM import from hidden folders

---

Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp

When ctkVTKAbstractView::scheduleRender calls decouples rendering requests from actual RenderWindow->Render() calls, to prevent repeated rendering pipeline updates when multiple Modified events are invoked in quick succession.
Minimum delay between RenderWindow->Render() calls was computed as
double msecsBeforeRender = 100. / d->RenderWindow->GetDesiredUpdateRate();
instead of the proposed corrected formula:
double msecsBeforeRender = 1000. / d->RenderWindow->GetDesiredUpdateRate();
Therefore, rendering requests are compressed when scheduleRender calls are 10x more than the desired update rate. Typically desired update rate is set to 30fps, which is approximately the screen refresh rate, therefore having a 10x multiplier (requests are started to be ignored over 300fps) is most likely a …

BUG: Fixed scheduleRender refresh rate computation in ctkVTKAbstractView

---

Libs/Widgets/ctkSearchBox.cpp

CTK rendered placeholderText even when built with Qt versions >= 4.7, while in these Qt versions Qt rendered placeholder text already.
On hi-DPI screens with Qt5, Qt rendered placeholderText in a slightly shifted position, which made duplicate rendering of the placeholderText by CTK and Qt very visible.
Fixed it by correcting the Qt version check (CTK paints placeholderText only when Qt version < 4.7.
Ghosting of placeholderText before the fix:

BUG: Fixed duplicate "Search" placeholder text in ctkSearchBox

---

Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.h
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView_p.h

Render window's DesiredUpdateRate property was used to determine maximum update rate of ctkVTKAbstractView. This had two issues:
1. VTK often significantly overestimates rendering time and so DesiredUpdateRate have to be set to quite low value (few fps) to get acceptable quality rendering. However, if ctkVTKAbstractView uses this value as maximum update rate, it would severely limit the achievable actual refresh rate. Separating the two values allow controlling quality settings and event compression separately.
2. When DesiredUpdateRate was set to "still update rate" (0.0001 fps; this is the default value) then rendering was never enforced. This caused indefinitely delayed rendering updates on MacOSX, when events were continuously generated on the GUI (e.g., by moving image slice selector …

BUG: Fixed maximum update rate computation in ctkVTKAbstractView

---

Libs/Widgets/ctkMessageBox.cpp

The messagebox was deleted twice (first because it was created on the stack, second time when the parent window was destroyed). This caused crash on exit.
Fixed by not creating the messagebox object on the stack and deleting by setting WA_DeleteOnClose flag.

BUG: Fixed crash during exit caused by ctkMessageBox::confirmExit

---

Libs/DICOM/Core/Testing/Cpp/ctkDICOMIndexerTest1.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMIndexer.h
Libs/DICOM/Core/ctkDICOMIndexer_p.h
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.h
Libs/DICOM/Widgets/ctkDICOMTableManager.h

IDs of last inserted patient, study, series items were cached in the ctkDICOMDatabase to avoid re-inserting when adding each file instance. However, if this patient, study, or series are removed from the database, then their IDs have to be cleared to force adding them back to the database when adding a file instance. Clearing of IDs when items are deleted has been implemented in ctkDICOMDatabase. The problems is that an application may use multiple database connections (ctkDICOMDatabase instances) to connect to the same database, and delete items corresponding to the cached IDs.
Fixed the problem by deleting cached item IDs once, just before a batch of instances are inserted to the database.
To define what is the beginning and end of a "batch", startIndexing and endIndexing method was …

BUG: Fixed failed re-import of DICOM images

---

Plugins/org.commontk.configadmin/Testing/Cpp/CMakeLists.txt

This commit fixes the error reported below when building CTK
with:
-DQt5_DIR:PATH=/path/to/Qt5 -DCTK_QT_VERSION:STRING=5 -DCTK_PLUGIN_org.commontk.configadmin:BOOL=1
```
In file included from /home/jcfr/Projects/CTK/Libs/PluginFramework/ctkPluginConstants.h:27:0,
from /home/jcfr/Projects/CTK/Plugins/org.commontk.configadmin/Testing/Cpp/ctkConfigAdminImplTestMain.cpp:26:
/home/jcfr/Projects/CTK-build/CTK-build/Libs/PluginFramework/ctkPluginFrameworkExport.h:11:37: fatal error: ctkCompilerDetections_p.h: No such file or directory
compilation terminated.
```
Fixes #802

COMP: Fix missing ctkCompilerDetections_p.h when building configadmin tests

---

Libs/Widgets/ctkSettingsPanel.cpp

This closes #799.
When settings are applied by pressing the "OK" button in the Settings Dialog, the changed settings indicator should be updated so that upon reopening the Settings Dialog there should be no changed settings indicators visible.  Currently, the indicator isn't updated after applying settings, so on showing the settings dialog again you have to toggle the setting to reset the indicator.
I've added a fix that emits the settingChanged signal when settings are applied so that it will then call the `updatePanelTitle` function for updating the changed settings indicator.

BUG: Fix incorrect changed settings indicator

---

Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp

Solves error:
(gcc 8.1)
```
/Software/Slicer/build-relwithdebinfo/CTK/Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp:378:45: error: invalid use of incomplete type ‘class vtkRenderWindowInteractor’
self->ScalarsToColorsView->GetInteractor()->Render();
^~
In file included from /Software/Slicer/build-relwithdebinfo/CTK/Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp:50:
/home/phc/Software/Slicer/build-relwithdebinfo/VTKv9/GUISupport/Qt/QVTKOpenGLWidget.h:31:7: note: forward declaration of ‘class vtkRenderWindowInteractor’
class vtkRenderWindowInteractor;
Software/Slicer/build-relwithdebinfo/CTK/Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp: In member function ‘void …
```

COMP: Missing header

---

Libs/PluginFramework/ctkPluginStorageSQL.cpp
Libs/PluginFramework/ctkPluginStorageSQL_p.h

Use thread-local database connections in ctkPluginStorageSQL.
Instead of the checkConnection() method that was called in nearly every other method before actually getting the connection, I refactored this into a getConnection() method. The getConnection() method creates a thread-local connection if it does not yet exist and then checks the connection. So it can be described more like "ensure connection", I guess.
getConnection() is also used in open(), as most of its logic moved into getConnection(). To retrieve only existing connections, getConnection() has an optional parameter just like QSqlDatabase::database().
Public API didn't change. If something goes wrong, the same exceptions are still thrown at the same locations. There's an additional const close() method, as closing can be …

Fix issue #814

---

CMake/ctkMacroSetupQt.cmake

This allow to remove the definition QFILEDIALOG_OPTIONS
in ctkDirectoryButton and ctkPathLineEdit, used to conserve
backwards compatibility.

ENH: Update minimum Qt4 to 4.7

---

Libs/Visualization/VTK/Widgets/CMakeLists.txt
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.h
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView_p.h
Libs/Visualization/VTK/Widgets/ctkVTKChartView.h
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKOpenGLNativeWidget.h

Since using typedef or #ifdef prevents the real class associated with
ctkVTKOpenGLNativeWidget from being wrapped in PythonQt, this commit creates
a derived class.
Note also that the use of Q_DECLARE_METATYPE and qRegisterMetaType was
considered but it revealed not to be a possible alternative.
See https://github.com/commontk/CTK/pull/828
Fixes #829
Co-authored-by: Andras Lasso <lasso@queensu.ca>

STYLE: Simplify code introducing "ctkVTKOpenGLNativeWidget.h"

---

Libs/Visualization/VTK/Widgets/Testing/Cpp/CMakeLists.txt
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKAbstractViewTest1.cpp
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.h
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView_p.h

The pauseRender function allows applications to pause the invocation of forceRender from scheduleRender calls.
Useful for temporarily disabling rendering until all elements of the view have been correctly set.
Unpausing will call scheduleRender if scheduleRender was called while the view was paused.
Also adds a test for pauses and unpausing rendering using a ctkVTKSliceView.
Related issue: https://github.com/openigtlink/SlicerOpenIGTLink/issues/61

ENH: Add pauseRender function to ctkVTKAbstractView

---

Libs/QtTesting/Resources/XML/XMLDescription.xsd
Libs/QtTesting/ctkQtTestingUtility.cpp.in
Libs/QtTesting/ctkQtTestingUtility.h
Libs/QtTesting/ctkXMLEventObserver.cpp
Libs/QtTesting/ctkXMLEventSource.cpp

Serialization of the recently added QtTesting event type attribute had two major issues: incorrect attribute name and attribute type. This pull request fixes both of them.
Since the attribute name is modified, this is not backward-compatible change. However, this should be negligible, as code has become functional only 5 days ago.
- Renamed "eventType" attribute to "type". It is redundant to have "event" in the name of the element and attribute. Before: <event eventType="..."/>. After <event type="..."/>
- Changed event type from integer magic number (0, 1) to string enum (action, check). Using magic numbers in files would make the format extremely inflexible and more difficult to interpret.

Fix QtTesting event type attribute saving to file

---

Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMIndexer.h

When ctkDICOMIndexer::addFile was called with non-empty destinationDirectoryName (to indicate that file should be copied) then "Ignoring destinationDirectoryName parameter, just taking it as indication we should copy!" warning message was logged for each file. This flooded the logs and had noticeable performance impact.
Since this warning is for developers, it is not necessary to log it for each file during runtime, but the behavior is documented instead in the header file.

ENH: Reduce warning logs during DICOM import

---

Libs/DICOM/Core/ctkDICOMItem.cpp

The locking mechanism for the dcmtk global
dictionary was changed to support:
Class OFReadWriteLock now uses SRW locks on Windows.
Unfortunately SRW locks require different functions for unlocking read
and write locks, which causes an API change in class OFReadWriteLock and
in class GlobalDcmDataDictionary (which internally uses a read/write
lock to protect access to the DICOM dictionary.)

COMP: DCMTK 3.6.4 updated function signatures

---

Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp

```cpp
[374/516] Building CXX object Libs/DICOM/Widgets/CMakeFiles/CTKDICOMWidgets.dir/ctkDICOMBrowser.cpp.o
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp: In member function ‘void ctkDICOMAppWidget::setDatabaseDirectory(const QString&)’:
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp:407:25: warning: catching polymorphic type ‘class std::exception’ by value [-Wcatch-value=]
catch (std::exception e)
```

COMP: Fix catch by value warning in ctkDICOMAppWidget

---

CMakeExternals/QtTesting.cmake

This adds a lot of bug fixes as well as new features.
Ctest ran and compared to master: no new test failure were reported

ENH: Update version of QtTesting

---

CMake/ctkMacroWrapPythonQtModuleInit.cpp.in

This commit avoids the error "SystemError: initialization
of CTK<LibName>PythonQt raised unreported exception"
from being reported when no PythonQt wrapper are associated
with <LibName>.
As discussed in [1], " module init functions should
return NULL in order to communicate that an exception
occurred during initialization"
[1] https://github.com/numpy/numpy/pull/10775#issue-176368003

BUG: Python3: Fix initialization of PythonQt module

---

.circleci/config.yml

This commit temporarily disables the failing test-qt4 and test-qt5 jobs.
See #854

ci: Disable testing

---

Libs/Core/CMakeLists.txt
Libs/Core/ctkErrorLogAbstractModel.cpp
Libs/Core/ctkErrorLogAbstractModel.h
Libs/Widgets/ctkErrorLogModel.cpp
Libs/Widgets/ctkErrorLogModel.h
Libs/Widgets/ctkErrorLogWidget.cpp
Libs/Widgets/ctkErrorLogWidget.h

This commit was motivated to support use of the log model from
qSlicerCoreApplication. This is needed to ensure messages are appended
to the log file during the unloading of modules following the call to
"factoryManager()->unloadModules()" from within the qSlicerCoreApplicationPrivate
destructor.
It is a follow up of f49c19a82 (move Widget dependent classes from Core
to Widgets. See #278)

Add ctkErrorLogAbstractModel to CTKCore library

---

Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorDefaultRule.cpp

The row and column DICOM tags were sometimes not precached in time for the displayed fields to contain the image size. This makes sure that these tags are always precached.

BUG: Fix DICOM image size computation

---

Libs/Widgets/ctkMatrixWidget.cpp
Libs/Widgets/ctkMatrixWidget.h

This allows customizing display of individual matrix elements, for example making last row of a homogeneous transformation matrix read-only.

ENH: Add direct access to widget items in ctkMatrixWidget

---

Libs/Core/Testing/Cpp/ctkLoggerTest1.cpp
Libs/Core/ctkUtils.h
Libs/Widgets/ctkMatrixWidget.cpp

Debug-mode Qt Designer crashed when tried to instantiate a ctkMatrixWidget because of an assert failure.
It may be useful to know that some operations fail, but making the Qt Designer crash is a too strong way of notifying developers (especially when developers only use CTK and not intend to fix its potential internal errors).
Fixed by converting assert to a debug log.
See user problem report here: https://discourse.slicer.org/t/designer-will-not-load-with-slicer-widgets/5496/4

Fix QtDesigner crash in debug mode

---

Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorAbstractRule.h

If a series description (or other field that is merged with mergeConcatenate) contained a comma, then it was concatenated even if it was the same. For example "first, second" was not found in the split fields because they were "first" and "second". Fixed by simply searching for the new value in the unsplit initial value.
There might be issues with this too, for example if if there are series descriptions like "first", "second", and also "first, second", but in that case seeing only "first, second" is acceptable.

BUG: Fix merging display table fields containing commas

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp

Re https://issues.slicer.org/view.php?id=4709

BUG: Escape single quote in DICOM database SQL statement

---

Applications/ctkDICOM/ctkDICOMMain.cpp
Applications/ctkDICOM2/ctkDICOM2Main.cpp
Applications/ctkDICOMHost/ctkDICOMHostMain.cpp
Applications/ctkDICOMQueryRetrieve/ctkDICOMQueryRetrieveMain.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMBrowserTest.cpp
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.h
Libs/Visualization/VTK/Widgets/Testing/Cpp/CMakeLists.txt
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKWidgetsUtilsTestImageConversion.cpp
Libs/Visualization/VTK/Widgets/ctkVTKWidgetsUtils.cpp
Libs/Visualization/VTK/Widgets/ctkVTKWidgetsUtils.h
Libs/Visualization/VTK/Widgets/ctkVisualizationVTKWidgetsPythonQtDecorators.h
Libs/Widgets/ctkPathLineEdit.h

Add utility function to convert Qt image to VTK image and fix a few Python wrappings.

Add qt to vtk image

---

CMakeExternals/PythonQt.cmake

* The list do not include the changes adding CMake support
```
$ git shortlog f0a6d6abc..c07f09fd --no-merges
Florian Link (54):
changed to native eol
allow to set PYTHON_VERSION as env variable fixed wrong library name
remove variadic functions
added parsing of rvalue references and skip functions that contain them (provided by erik_lundin@users.sf.net)
improved slot docs as provided from forum
changes to the build scripts as provided on the forum (not tested)
added unix pkg config as provided on forum
added support for kwargs by supporting QVariantMap kwargs as last argument, refactored from forum
added convenience evalScript
fixed unicode code and filename support for Python 3
added getNativeVariable
added experimental support for qwebenginewidgets (not yet in QtAll) …
```

ENH: Update PythonQt

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMIndexer_p.h
Libs/DICOM/Core/ctkDICOMItem.cpp
Libs/DICOM/Core/ctkDICOMItem.h
Libs/DICOM/Widgets/ctkDICOMTableView.cpp

Allow defining cached tags that are not stored in the DICOM tag cache by value. This prevents excessive memory usage and file reading for tags that are not appropriate to store in the tag cache (such as pixel data) but it is still possible to query if the tag is present.
Force updating the database after a certain number of files are parsed. This limits the total memory usage, which could grew big when hundreds of thousands of files were parsed in one batch.
Do not show all series when the browser is initially shown, as this can take significant amount of time when a large database is loaded.

ENH: Reduce memory usage of DICOM indexer

---

Libs/Visualization/VTK/Widgets/ctkVTKColorTransferFunction.h
Libs/Visualization/VTK/Widgets/ctkVTKPiecewiseFunction.cpp
Libs/Visualization/VTK/Widgets/ctkVTKPiecewiseFunction.h
Libs/Widgets/ctkTransferFunction.h
Libs/Widgets/ctkTransferFunctionBarsItem.cpp
Libs/Widgets/ctkTransferFunctionBarsItem.h
Libs/Widgets/ctkTransferFunctionItem.h
Libs/Widgets/ctkTransferFunctionRepresentation.h

The signals emitted by the ctkTransferFunctionItem provide two values, the function position (x and y values of the function at the location under the mouse), and the button that was pressed.
Additional changes include the wrapping of additional methods in ctkVTKPiecewiseFunction and ctkVTKColorTransferFunction, as well as a function to set the log mode in ctkTransferFunctionBarsItem.

ENH: Emit signals from ctkTransferFunctionItem for mouse events

---

Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp

When user requested view from a selected axis, the camera distance from the focal point was changed, too. This distance change caused unexpected field of view change (in perspective projection mode) and unexpected lighting change (in parallel projection mode, see https://discourse.slicer.org/t/shading-changes-with-default-orientation-buttons-at-different-zooms/8907/7).
Changed the behavior to keep the distance from the focal point constant and just change the direction we look from.

BUG: Fix unexpected camera position change in ctkVTKRenderView::lookFromAxis

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp

S. https://github.com/commontk/CTK/commit/7f2f24a051fd58118e9d6ddb464eaf085ec05853#r35829525
Thanks.

BUG: typo in ctkDICOMDatabase

---

Libs/DICOM/Core/Testing/Cpp/ctkDICOMIndexerTest1.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Widgets/ctkDICOMTableView.cpp

On some builds, application crashed when opening old databases. Could not reproduce it on applications built on developer computer.
Added check for presence of displayed fields table (isDisplayedFieldsTableAvailable) and if the table is missing then table view is not attempted to be populated with data.

BUG: Attempt to fix crash when opening database created with old schema

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Widgets/ctkDICOMTableView.cpp
Libs/DICOM/Widgets/ctkDICOMTableView.h

ENH: Add python accessibility for DICOM table view functions
ENH: Allow query of any field from DICOM database

Accessibility improvements in DICOM classes

---

Libs/DICOM/Widgets/ctkDICOMObjectModel.cpp

ctkDICOMObjectModel displayed the raw data buffer. Now we use ctkDICOMItem::Decode to convert raw data to UTF-8.

BUG: Fix special character display in DICOM metadata viewer

---

Libs/DICOM/Core/Resources/dicom-schema.sql
Libs/DICOM/Core/ctkDICOMDatabase.cpp

Many times it is useful to be able to order patients with last study date. This display field has now been added.

ENH: Add patient display field for last study date

---

Libs/Widgets/Testing/Cpp/ctkCheckablePushButtonTest1.cpp
Libs/Widgets/ctkCheckablePushButton.cpp
Libs/Widgets/ctkCheckablePushButton.h

If checkBoxControlsButtonToggleState is enabled then clicking the checkbox also makes the button pushed (for user's convenience) and unpushing the button makes it unchecked, too (to avoid the ambiguous state when the button's checkbox is checked but the button is not pressed down).
The property is disabled for now to preserve the current behavior (for backward compatibility).
Co-authored-by: Kyle Sunderland <sunderlandkyl@gmail.com>
Replaces https://github.com/commontk/CTK/pull/899

ENH: Add checkBoxControlsButtonToggleState property to ctkCheckablePushButton

---

Libs/DICOM/Widgets/ctkDICOMThumbnailGenerator.cpp
Libs/DICOM/Widgets/ctkDICOMThumbnailGenerator.h

- Add width and height properties to ctkDICOMThumbnailGenerator to explicitly specify thumbnail size for different views
- Change default thumbnail size from 128x128 to 256x256
- Add smoothResize property in ctkDICOMThumbnailGenerator to allow better quality thumbnail image (by default it is off, so resizing is fast but crude)
- Fix style (indentation, etc)
- Add generateThumbnail with path argument instead of DicomImage, to allow direct python access

ENH: Allow setting DICOM thumbnail dimensions and resize function

---

Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp
Libs/Widgets/ctkConsole.cpp
Libs/Widgets/ctkConsole.h
Libs/Widgets/ctkConsole_p.h

Make console message printing methods (printMessage, printOutputMessage, printErrorMessage) available in Python.
This is useful for example when custom display hook is used in Python and output is not redirected to stderr/stdout.
See https://github.com/Slicer/SlicerJupyter/pull/38 for information about how it is used.

ENH: Make console message printing methods available in Python

---

Libs/DICOM/Core/Testing/Cpp/ctkDICOMIndexerTest1.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMBrowserTest.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMBrowserTest1.cpp
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.h

In some cases, it is necessary to load individual files and not an entire folder into the DICOM database.

ENH: Add method to import selected files into DICOM browser

---

Applications/ctkXnatTreeBrowser/ctkXnatTreeBrowserMainWindow.ui
Libs/DICOM/Widgets/Resources/UI/ctkDICOMTableView.ui

With recent Qt versions, such as Qt-5.15, the special font set in the DICOM browser (in ctkDICOMTableView) does not get rendered correctly on Windows.
It is safer to remove this special font setting in CTK. It can be overridden set by the application anyway.
The only other place where font style was set in CTK was in ctkXnatTreeBrowserMainWindow. For consistency, the font setting has been removed from there, too.
Fixes https://github.com/Slicer/Slicer/issues/4951

BUG: Fix font style in DICOM browser

---

Libs/Widgets/ctkMessageBox.cpp
Libs/Widgets/ctkMessageBox.h

QMessageBox::done(int) is not called after Qt-5.12 (see https://bugreports.qt.io/browse/QTBUG-74699), so use onFinished(int) signal instead.
This new mechanism would probably work with earlier Qt versions, too, but we keep using the old way for earlier Qt versions to avoid any potential regressions.

BUG: Fix ctkMessageBox don't show again feature in Qt-5.12

---

Libs/Core/CMakeLists.txt
Libs/Core/Testing/Cpp/CMakeLists.txt
Libs/Core/Testing/Cpp/ctkCoreSettingsTest.cpp
Libs/Core/ctkCoreSettings.cpp
Libs/Core/ctkCoreSettings.h
Libs/Widgets/ctkSettings.cpp
Libs/Widgets/ctkSettings.h

ctkCoreSettings allows storing paths relative to an "application home" folder. This makes it easy to create fully portable applications (that do not have absolute paths in application settings).
It will be used with this development in 3D Slicer: https://github.com/Slicer/Slicer/pull/5029

ENH: Allow saving relative paths to settings

---

Libs/DICOM/Widgets/Resources/UI/ctkDICOMTableManager.ui

When switching style using palettes as part of some work in 3D Slicer to implement Light and Dark modes this defined stylesheet in the ctkDICOMTableManager was messing things up by not changing when the style in 3D Slicer was dynamically changed after startup. It was flip-flopping and using the previous palette color instead of the currently specified one.  Removing this stylesheet solves this issue.
Note to see these exact results in Slicer, one must use the latest of https://github.com/Slicer/Slicer/pull/4993.
| On startup | After changing style (the issue) | After changing style with this PR |
|-------------|------------------------------------|---------------|
|![image](https://user-images.githubusercontent.com/15837524/88465271-a6a99c00-ce8f-11ea-889c-b1bbeda6a0a9.png)|![image](https: …

BUG: Fix DICOM table defined stylesheet messing up use with palette

---

Libs/Widgets/ctkBasePopupWidget.cpp

Popup widgets created with default settings (ScrollEffect) often cause crashes when used with Qt-5.15.0 on macOS.
https://github.com/Slicer/Slicer/issues/5092
Changed default animation effect to FadeEffect, which works robustly.
Also changed default effect duration to 30ms, as user complained that popup window display was too sluggish.
Since popup widgets are only used in 3D Slicer and application crash is a serious issue, I would merge this tonight before the nightly build cutoff time (10pm).

BUG: Fix crash in popup widgets with Qt-5.15

---

Libs/Widgets/Testing/Cpp/ctkPathLineEditTest1.cpp
Libs/Widgets/ctkPathLineEdit.cpp

Each ctkPathLineEdit widget created a QFileSystemModel for auto-complete, which overloaded Linux and Mac systems.
Instead, now we use a shared QFileSystemModel for all instances (similar to how it is done in ParaView) and a custom QFileSystemModel is only created if it strictly necessary (when name filter is set).

BUG: Fix crash when man instances of ctkPathLineEdit is instantiated

---

Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKWidgetsUtilsTestImageConversion.cpp

This commit fixes the following error:
/path/to/CTK/Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKWidgetsUtilsTestImageConversion.cpp:28:21: fatal error: QPixmap.h: No such file or directory

COMP: Fix build of ctkVTKWidgetsUtilsTestImageConversion using Qt 5.10

---

Libs/Visualization/VTK/Core/CMakeLists.txt
Libs/Visualization/VTK/Widgets/CMakeLists.txt
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKAbstractViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKChartViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKMagnifyViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKRenderViewEventTranslatorPlayerTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKRenderViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKRenderViewTest2.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsViewTest2.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsViewTest3.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsWidgetTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsWidgetTest2.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsWidgetTest3.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKSliceViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKSliceViewTest2.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKThumbnailViewTest1.cpp
Libs/Visualization/VTK/Widgets/ctkVTKWidgetsUtils.cpp
Libs/Visualization/VTK/Widgets/ctkVTKWidgetsUtils.h

Changes to support build with VTK 9.0
In VTK 9.0 QVTKOpenGLWidget is deprecated and should be replaced by QVTKOpenGLNativeWidget. Additional library references are required in VTK/Core and VTK/Widget.
Changes tested under Win10 with external build VTK 9.0.1.

Adding support for VTK 9.0

---

Libs/Visualization/VTK/Core/vtkLightBoxRendererManager.cpp

Waiting issue Slicer/Slicer#5220 is resolved, accept that other actors
like corner annotations and crosshairs are occluded and ensure image
data is displayed.
See https://github.com/Slicer/Slicer/issues/5220

BUG: Workaround slice viewer rendering issue when built against VTK9

---

Libs/Visualization/VTK/Core/vtkLightBoxRendererManager.cpp

This reverts commit 2f164d767f8d944d2565f9a08ace91f779e6f142.
See https://github.com/Slicer/Slicer/pull/5272#issuecomment-717663125

BUG: Revert invalid workaround for slice viewer issue with VTK9

---

Libs/Widgets/Testing/Cpp/ctkMessageBoxDontShowAgainTest.cpp
Libs/Widgets/ctkMessageBox.cpp
Libs/Widgets/ctkMessageBox.h

Previously, when dontShowAgain flag was enabled, only buttons with AcceptRole could be saved in settings.
Now the user can customize the list of button roles.
For example Yes and No button choice can be saved, while still not saving anything if user clicks Cancel.

ENH: Allow ctkMessageBox to store any don't-show-again button roles in settings

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h

Study, series, and SOP instance UIDs were used to generate path for data sets copied into the DICOM database.
When database folder path or UIDs were long, this path length could very easily become longer than the file system maximum path limit
(about 256 characters on some systems, for example on Windows or when writing CDs).
Added useShortStoragePath flag so that developers can still switch between full and shortened paths.

ENH: Reduce storage path length of files stores in DICOM database

---

Libs/Core/Testing/Cpp/ctkUtilsCopyDirRecursivelyTest1.cpp
Libs/Core/ctkUtils.cpp
Libs/Core/ctkUtils.h

This should fix https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/issues/54#issuecomment-728375173

Ensure copyDirRecursively considers hidden directories and files

---

Libs/Visualization/VTK/Core/ctkVTKConnection.cpp

ctkVTKConnection logged a warning message each time an event was received that vtkObject* as event data and the pointer was nullptr.
Always treating nullptr value as an error is too limiting, because it is often useful that an additional pointer can be supplied but not mandatory.
This change removes the warning message from ctkVTKConnection and makes it the event receiver's responsibility to log warning/error if in that particular case nullptr is not expected.
Since ctkVTKConnection just logged a warning message but already left nullptr values through, it is guaranteed that change does not alter any existing software behavior
(other than not displaying the warning).
This change is useful in Slicer because DisplayModified events typically contain the display node pointer as eventdata but …

ENH: Remove warning message when nullptr is used as vtkObject pointer event data

---

Libs/Widgets/ctkConsole.cpp
Libs/Widgets/ctkConsole.h

Previously, the API allowed execution of commands but not
setting the state of the command buffer to be executed when the
user hit enter.
Also the command history always started empty.
This change adds read/write properties to fix this.
Now the command buffer can be set, e.g. by a hot key or other
custom code and it will be editable and the user can add more text,
user the completer, etc.
Also the command history can be controlled by the appication so
that it can save and restore previous sessions as a convenience
to the user.

ENH: add command and history properties to ctkConsole

---

Libs/Core/ctkCorePythonQtDecorators.h
Libs/Core/ctkUtils.cpp
Libs/Core/ctkUtils.h
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.h

Previously full path was stored to DICOM files that were copied into the DICOM database. This made it impossible to move the database into any other location or store in on removable storage (such as a USB stick, which may be mapped with different path on different computers).
Now files that are copied (not linked) to the DICOM database are stored with path relative to the DICOM database folder (where the .sql files are located).
Also, DICOM database location can now be specified with relative path in application settings. This allows the database to be moved along with the application. For example, to implement a DICOM viewer that opens DICOM database in a folder relative to the application's location (e.g., use the application as a viewer on a DICOM CD).
FYI @cpinter @jcfr

ENH: Make DICOM database relocatable

---

Libs/DICOM/Widgets/ctkDICOMBrowser.cpp

When exporting a DICOM series from the database to the file system, subfolders are created from DICOM fields content.
Sanitization of DICOM fields to be used as filename was not sufficient (allowed various non-ASCII and special characters).

Improve filename sanitization in DICOM export

---

Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Widgets/ctkDICOMTableView.cpp
Libs/DICOM/Widgets/ctkDICOMTableView.h

In addition to filtering for field values, now it is possible to define where conditions that use the operators 'greater', 'less', 'greater or equal', and 'less or equal'.
For example `addSqlGreaterEqualWhereCondition("Series.SeriesDate", "2020-01-01")`.
The SQL query is now assembled using a [QSqlQuery](https://doc.qt.io/qt-5/qsqlquery.html) and its value binding feature instead of setting the query directly from string, thus making it safer.
For consistency, alias functions have been added for the old where condition functions while keeping those for backwards compatibility (i.e. `addSqlWhereCondition` -> `addSqlEqualWhereCondition`, `removeSqlWhereCondition` -> `removeSqlEqualWhereCondition`)
Functions have been added to remove all types of where conditions individually, as well as one …

ENH: Additional where conditions in DICOM table view; Safer SQL query

---

Libs/Visualization/VTK/Widgets/ctkVTKThresholdWidget.cpp

BUG: Fix ctkVTKThresholdWidget 'pow' was not declared

---

Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.h

X axis of scalar opacity and color transfer functions is image intensity, so it makes sense to shift them together along the x axis.
However, x axis of gradient opacity transfer function is the image intensity gradient, therefore it should not be changed when the image is offset along x axis.

ENH: Make gradient opacity transfer function shift independently from opacity and color transfer functions

---

Libs/DICOM/Core/ctkDICOMItem.cpp

When DICOM strings could not be decoded (because an unsupported encoding was used) then it was assumed to be encoded as Latin1.
This led to incorrect special characters appearing in the output and in some cases even invalid UTF8 string (causing data corruption - see https://discourse.slicer.org/t/re-failure-to-opening-saved-work/17473/5).
As a workaround, to make decoding issues more visible and avoid having random non-ASCII characters appearing in the output, we replace non-ASCII characters by '?'.
As a proper solution, DCMTK could be used to convert from all DICOM standard encodings. However, for this DMTK must be built with iconv, which seems to be quite complicated (mostly DCMTK's build system handles third-party dependencies in unusual way). Since non-supported encodings are very …

BUG: Remove invalid characters from DICOM strings with unsupported character encoding

---

Libs/DICOM/Core/CMakeLists.txt
Libs/DICOM/Core/Resources/dicom-schema.sql
Libs/DICOM/Core/ctkDICOMCorePythonQtDecorators.h
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGenerator.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGenerator.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorAbstractRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorDefaultRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorDefaultRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorLastStudyDateRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorLastStudyDateRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorPatientNumberOfStudiesRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorPatientNumberOfStudiesRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRadiotherapySeriesDescriptionRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRadiotherapySeriesDescriptionRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRuleFactory.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRuleFactory.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorSeriesImageCountRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorSeriesImageCountRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorStudyNumberOfSeriesRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorStudyNumberOfSeriesRule.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGenerator_p.h

- DICOM displayed rules are created for every new database using a factory class
- Allows the indexer to use an up-to-date list of generator rules when updating the displayed fields after importing new data
- The displayed field generator sets up the displayed field rules when setting the database, and also on each startUpdate so that it always has an up-to-date rule list
- The factory uses a new DisplayedFieldGeneratorRules table in the database for providing the proper rule set
- The table defines for each rule (by name) whether they are enabled and may provide an options string (for later use)
- Database schema version has been increased to 0.7.0
- If the table does not exist (e.g. using another or a custom schema) or if there is no entry for a rule (omitted from the list for any …

ENH: Add DICOM displayed field generator rule factory

---

Libs/Widgets/ctkMatrixWidget.cpp

Each time a ctkMatrixWidget was shown, a series of errors about width and height mismatch flooded the log, making it harder to read. Since these mismatches do not seem to have any consequence on function, it seems to be more advantageous to remove the asserts.

BUG: Remove assert from matrix widget that flooded application log

---

Libs/Widgets/ctkFileDialog.cpp

This aims to improve directory selection by using the native dialog instead of Qt's own widget-based dialog design.
See 3D Slicer forum discussion of how users have been doing other methods to avoid using widgets that use Qt's widget-based dialog.
https://discourse.slicer.org/t/using-native-file-dialog-for-selecting-files-and-folders/17926
| Qt widget-based dialog | Native dialog (on Windows)|
|-------------------------|--------------------------------|
|![image](https://user-images.githubusercontent.com/15837524/120825251-3051dd80-c527-11eb-83a4-1a0c2c03971c.png)|![image](https://user-images.githubusercontent.com/15837524/120825677-9e96a000-c527-11eb-8200-2c2a4cecc8ae.png)|

ENH: Improve usability of Directory Button by using native dialog

---

Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/Widgets/ctkFileDialog.cpp

Following up to https://github.com/commontk/CTK/pull/973, this makes changes for ctkDICOMBrowser to not crash on initialization. @lassoan Would you like to make the additional DICOM related changes here now that the "Copy" import mode wouldn't be used? I'm a user that does not do any DICOM work so I do not know what would be appropriate behavior.

BUG: Fix crash instantiating ctkDICOMBrowser

---

CMakeExternals/PythonQt.cmake

This commit fixes the following error reported when trying to install
light-the-torch in Slicer:
```
AttributeError: 'PythonQtStdInRedirect' object has no attribute 'isatty'
```
See https://github.com/Slicer/Slicer/issues/5705
```
$ git shortlog dafdb72..c306140 --no-merges
Andras Lasso (1):
[Backport] Add isatty() method to PythonQtStdIn class
```

BUG: Update PythonQt to fix intallation of light-the-torch in Slicer

---

Libs/Widgets/ctkFileDialog.cpp

This closes #980.
Using my Windows machine and testing with 3D Slicer I was able to successfully import a file to the DICOM browser. 
Previously it would crash upon selecting the "Import" button of the native dialog.

BUG: Fix crash upon selecting files with DICOM browser import dialog

---

Libs/DICOM/Widgets/ctkDICOMBrowser.cpp

After recent changes to allow native file browsers,
clicking the button would apparently create a dialog
on mac but it was not visible.  Because it was modal
the app would be alive but unresponive.
This change replaces show() and raise() which work
for QDialog with exec() which is apparently needed
for the native dialog to work properly.
https://discourse.slicer.org/t/slicer-is-freezing-on-macos-when-clicking-on-import-dicom-files/18624
Co-authored-by: Andras Lasso <lasso@queensu.ca>

BUG: avoid app freeze on mac

---

Libs/Core/ctkUtils.cpp
Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.cpp

Fixes in volume rendering properties widget and path conversion utility functions

---

Libs/DICOM/Core/ctkDICOMQuery.cpp

This small change adds "AccessionNumber" support in DICOM queries

ENH added AccessionNumber to Filters 

---

Libs/DICOM/Core/ctkDICOMRetrieve.h

BUG: Fix ctkDICOMRetrieve::calledAETitle property setting method

---

Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.h
Libs/DICOM/Widgets/ctkDICOMTableManager.cpp
Libs/DICOM/Widgets/ctkDICOMTableManager.h
Libs/DICOM/Widgets/ctkDICOMTableView.cpp
Libs/DICOM/Widgets/ctkDICOMTableView.h

Allow selecting patient/study/series in the DICOM browser GUI.
This is can be used for example for highlighting new items after DICOM import.

ENH: Add API to select items in the DICOM browser

---

Libs/Core/Testing/Cpp/ctkUtilsTest.cpp
Libs/Core/ctkUtils.cpp
Libs/Core/ctkUtils.h

These functions are useful to support building against `Qt>=5.14` and avoid
warnings like the following:
```
/path/to/S/Base/QTApp/qSlicerApplicationHelper.txx:170:55: warning: 'toSet' is deprecated: Use QSet<T>(list.begin(), list.end()) instead. [-Wdeprecated-declarations]
moduleFactoryManager->registeredModuleNames().toSet() - moduleFactoryManager->instantiatedModuleNames().toSet());
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qlist.h:412:5: note: 'toSet' has been explicitly marked deprecated here
QT_DEPRECATED_VERSION_X_5_14("Use QSet<T>(list.begin(), list.end()) instead.")
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qglobal.h:366:45: note: expanded from macro 'QT_DEPRECATED_VERSION_X_5_14'
^ …
```

Update ctkUtils adding qListToQSet and qSetToQList 

---

CMake/ctkMacroGenerateMocs.cmake

This commit prepare the transition to Qt6 by fixing warnings like the following:
```
CMake Warning (dev) at /path/to/Support/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:44 (message):
qt5_get_moc_flags is not part of the official API, and might be removed in
Qt 6.
Call Stack (most recent call first):
/path/to/Support/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:86 (_qt5_warn_deprecated)
/path/to/Projects/S-r-v8/CTK/CMake/ctkMacroGenerateMocs.cmake:8 (QT5_GET_MOC_FLAGS)
/path/to/Projects/S-r-v8/CTK/CMake/ctkMacroGenerateMocs.cmake:43 (QT4_GENERATE_MOCS)
Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt:41 (QT5_GENERATE_MOCS)
```
```
CMake Warning (dev) at /path/to/Support/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:44 (message): …
```

COMP: Update ctkMacroGenerateMocs to fix warnings using qt5_generate_moc

---

Applications/ctkCommandLineModuleExplorer/ctkCmdLineModuleExplorerTreeWidget.cpp
Libs/Core/ctkModelTester.cpp
Libs/Core/ctkUtils.cpp
Libs/Core/ctkUtils.h
Libs/DICOM/Core/ctkDICOMModel.cpp
Libs/DICOM/Widgets/ctkDICOMItemView.cpp
Libs/DICOM/Widgets/ctkDICOMThumbnailListWidget.cpp

This commit introduces ctk::modelChildIndex() function so that the
same code compiles without deprecation warnings pre and post Qt 5.8.
It fixes warnings like the following:
```
/path/to/S-r/CTK/Libs/DICOM/Core/ctkDICOMModel.cpp:745:32: warning: 'child' is deprecated: Use QAbstractItemModel::index [-Wdeprecated-declarations]
this->setChildData(index.child(i,0), value, role);
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h:71:5: note: 'child' has been explicitly marked deprecated here
QT_DEPRECATED_X("Use QAbstractItemModel::index") inline QModelIndex child(int row, int column) const;
^
/path/to/Support/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
^ …
```

COMP: Fix QModelIndex::child() deprecation warnings

---

Libs/Core/ctkUtils.cpp
Libs/Core/ctkUtils.h

This will avoid explicit use of `const_cast` when function `ctk::modelChildIndex`
is called from const functions.

Add ctk::modelChildIndex implementation accepting const model

---

Libs/Widgets/Testing/Cpp/ctkDirectoryButtonTest1.cpp
Libs/Widgets/Testing/Cpp/ctkPushButtonTest.cpp
Libs/Widgets/ctkDirectoryButton.cpp
Libs/Widgets/ctkDirectoryButton.h
Libs/Widgets/ctkPathLineEdit.cpp
Libs/Widgets/ctkPathLineEdit.h
Libs/Widgets/ctkPushButton.cpp
Libs/Widgets/ctkPushButton.h
Libs/Widgets/ctkPushButton_p.h

Directory paths are often very long, which can force very wide GUI layouts if the full path is displayed.
To avoid this, ctkDirectoryButton now enables eliding by default (display beginning and end of the path with ... in the middle),
so that if the user sets size policy to Ignored then the button will not be wide and will display a correctly shortened path.

Add elide option to ctkPushButton and make ctkDirectoryButton elided by default

---

Libs/Widgets/ctkLanguageComboBox.cpp
Libs/Widgets/ctkLanguageComboBox.h

- Added `directories` property to specify multiple folders to scan for translation (*.qm) files (before that only one directory could be specified).
- Added `countryFlagsVisible` property to display "country" name instead of country flag, because not all region is a country with a flag (e.g., Latin America).
- Updated the logic that determines if country name (or flag) should be shown: if a translation of a language is only available for one region then the region name is not displayed. This avoids redundant item text such as "Hungarian (Hungary)" (it is just displayed as "Hungarian").
Example of countryFlagsVisible=false:

ENH: Improve ctkLanguageComboBox

---

CMakeExternals/DCMTK.cmake
CMakeExternals/ITK.cmake
CMakeExternals/VTK.cmake

Tested on Windows10, MSVC16, VS2019. 
There are some issues with DCMTK. When compling DCMTK related plugins, it is required to put compiled libraries in some project folder to be able to continue compling.

ENH: Add option on using system library

---

Libs/Visualization/VTK/Widgets/ctkVTKSurfaceMaterialPropertyWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKSurfaceMaterialPropertyWidget.h
Libs/Widgets/Resources/UI/ctkMaterialPropertyWidget.ui
Libs/Widgets/ctkMaterialPropertyPreviewLabel.cpp
Libs/Widgets/ctkMaterialPropertyPreviewLabel.h
Libs/Widgets/ctkMaterialPropertyWidget.cpp
Libs/Widgets/ctkMaterialPropertyWidget.h

ctkMaterialPropertyWidget can now edit material properties for both non-PBR (Phong, Gouraud) and PBR interpolation.
PBR material properties are `diffuse` (shared with non-PBR modes) and `metallic` and `roughness` (matching names used in VTK and glTF).
An interpolation mode selector is added (hidden by default for backward compatibility) to allow easy switching between interpolation modes.
ctkVTKSurfaceMaterialPropertyWidget is updated to get/set associated properties in VTK.
ctkMaterialPropertyPreviewLabel is updated so that it can display both PBR and non-PBR material settings. Preview of PBR settings is a rough approximation.
Example of PBR rendering in 3D Slicer:

ENH: Add support for PBR material properties in material property widgets

---

Libs/Widgets/ctkPathLineEdit.cpp

The focus proxy is set to the `QLineEdit`, which is a natural choice.
This way the user of `ctkPathLineEdit` can set its focus policy and
include in a tabbing order as though it's a single widget, without
thinking about the underlying QWidgets internal to `ctkPathLineEdit`.
Related discussion: https://github.com/Slicer/Slicer/pull/6184#issuecomment-1045592937

ENH: Set focus proxy on ctkPathLineEdit

---

CMake/ctkDashboardDriverScript.cmake
CMakeExternals/Log4Qt.cmake
CMakeExternals/PythonQt.cmake
CMakeExternals/QtSOAP.cmake
CMakeExternals/QtTesting.cmake
CMakeExternals/ZMQ.cmake
CMakeExternals/qRestAPI.cmake
CMakeExternals/qxmlrpc.cmake

Considering that since March 2022, git protocol is not supported any more
by GitHub, this commit updates external projects to explicitly use "https"
protocol.
See https://github.blog/2021-09-01-improving-git-protocol-security-github/
Co-authored-by: Andras Lasso <lasso@queensu.ca>

STYLE: Explicitly associate "https" protocol with GitHub external projects

---

Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp

Camera clipping range must be reset after camera motion.
Fixes issue described here: https://discourse.slicer.org/t/extremities-of-a-long-volume-vanishing-when-rotating/23234/10?u=lassoan

BUG: Fix clipped view content when rotating view

---

Libs/Visualization/VTK/Core/vtkLightBoxRendererManager.cpp

Following kitware/VTK@d933bb849 (vtkDeprecation: remove symbols deprecated
in 9.1), file "vtkConfigure.h" has been removed.
Since the use of vtkConfigure.h was superseded by the introduction of
vtkVersion.h in c68324047 (ENH: Support VTK6 in CTK) and became obsolete
with the removal of VTK5 support in e419ceeeb (COMP: Remove support
for building against VTK <= 5.8), this commit fixes the build by removing
the include.

COMP: Fix build against VTK > 9.1 removing use of removed "vtkConfigure.h"

---

Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKChartView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKMagnifyView.cpp

Following kitware/VTK@d933bb849 (vtkDeprecation: remove symbols deprecated
in 9.1), the "vtkDeprecation.h" header (itself including "vtkVersionMacros.h"
was removed from "vtkOpenGLRenderWindow.h". This commit fixes the related
build errors by explicitly including "vtkVersion.h" and ensure that
the macro like VTK_MAJOR_VERSION and VTK_MINOR_VERSION are defined.

COMP: Fix build against VTK > 9.1 explicitly including "vtkVersion.h"

---

Libs/Core/ctkErrorLogAbstractModel.cpp
Libs/Core/ctkErrorLogAbstractModel.h

This API is useful for accessing message handlers, for example to connect to messageHandled signals.

ENH: Add API to get message handler from ctkErrorLogAbstractModel

---

Libs/Core/ctkErrorLogAbstractModel.cpp
Libs/Core/ctkErrorLogAbstractModel.h
Libs/Core/ctkErrorLogLevel.cpp
Libs/Core/ctkErrorLogLevel.h
Libs/Widgets/ctkConsole.cpp

These changes allow applications to capture all log messages from the error log model (messages can be injected by calling `postEntry`; and captured by using the new `entryAdded` signal) and display them in the console. See  for example: https://github.com/Slicer/Slicer/pull/5156#issuecomment-1278471951
- Added `postEntry` method to log events directly, without going through a message handler, but using the same connection mechanism as message handlers (to ensure logging of messages in the correct order).
- Added `entryAdded` signal that provides full log entry information (not just the log level as the existing signal). This can be used for displaying log messages in an additional widget, such as the Python console.
- Modified ctkConsole's command execution method to allow displaying …

ENH: Improve error log model API to allow log display in console

---

Libs/Widgets/ctkConsole.cpp

These two commits address several small limitations of the Python console.

Console improvements

---

Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp
Libs/Scripting/Python/Widgets/ctkPythonConsole.h
Libs/Widgets/ctkConsole.cpp
Libs/Widgets/ctkConsole.h
Libs/Widgets/ctkConsole_p.h

When a complete string of command is executed (either copy-pasting or running from file) then we no longer split the string to lines and execute line by line because that often leads to errors. For example, parsing of this Python code line by line would fail due to the empty line in the function definition:
```
def test1():
print("one")
print("two")
print("three")
def test2():
print("ok")
```
Also make the console remember the path of the last run Python file to make it easier to run it again.
Before this fix (failure while trying to specify `test1()` function):
After the fix (everything works as expected):

ENH: Improve robustness of Python code running in the console

---

Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKRenderViewTest1.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKRenderViewTest2.cpp
Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKRenderView.h

The fov parameter became obsolete following d620ad9 (BUG: Fix
unexpected camera position change in ctkVTKRenderView::lookFromAxis)

COMP: Fix -Wunused-parameter in ctkVTKRenderView::lookFromAxis()

---

Libs/Visualization/VTK/Widgets/ctkVTKHistogram.cpp

When the input image of ctkVTKHistogram was empty then resetRange() logged a warning. An empty image is a valid input (the histogram should be empty) and resetRange() operation is valid on the empty histogram, too. Therefore, it is not necessary to log a warning.
Removing the warning reduces noise during normal operation, which helps in detecting real problems.

BUG: Fix unnecessary warning in ctkVTKHistogram::resetRange()

---

Libs/Widgets/ctkConsole.cpp

When error messages were printed during auto-complete, the error messages got mixed up with the entered command.
Fixed by inserting text into the correct position (this->textCursor()  was called twice in ctkConsolePrivate::printString() and so the movePosition() call had no effect); also changed the code to use this->textCursor() consistently to get the cursor (sometimes the equivalent `QTextCursor c(this->document())` call was used)
Also fixed output printing: always print pending messages before displaying the prompt.
see https://github.com/Slicer/Slicer/issues/6630

BUG: Fix cursor position during auto-complete

---

Libs/DICOM/Core/ctkDICOMDatabase.h

In automated tests it could be useful to explicitly clear the cache. This change allows doing that.

ENH: Expose removeCachedTags method in Python

---

Libs/DICOM/Widgets/ctkDICOMQueryRetrieveWidget.cpp

After multiple queries with different criteria, the query/retrieve widget crashed due to null-pointer dereference. It was not clear what led to the error, but the null-pointer check in this commit prevents the application from crashing, which is already an improvement.

BUG: Fix crash in ctkDICOMQueryRetrieveWidget

---

Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp
Libs/Scripting/Python/Widgets/ctkPythonConsole.h

Having ctkPythonConsoleCompleter class available on the public API allows applications to create custom completer implementations derived from this class.
For example, this is used in 3D Slicer to get completions with temporarily disabled logging during querying object properties. Temporary suppression of logging is needed because querying object properties leads to executing property getter methods in PythonQt objects. These getter methods may log errors/warnings because the method is deprecated or some inputs in the object have not been set yet. See https://github.com/Slicer/Slicer/issues/6785.
fixes #1054

ENH: Expose ctkPythonConsoleCompleter on the public CTK API

---

Libs/DICOM/Widgets/Resources/UI/ctkDICOMObjectListWidget.ui
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMObjectListWidget.cpp
Libs/DICOM/Widgets/ctkDICOMObjectListWidget.h
Libs/DICOM/Widgets/ctkDICOMThumbnailGenerator.cpp
Libs/DICOM/Widgets/ctkDICOMThumbnailGenerator.h
Libs/Widgets/ctkExpandButton.cpp
Libs/Widgets/ctkExpandButton.h

This pull request adds image thumbnail display to the DICOM metadata viewer window:
This pull request replaces the WIP pull request by @pieper - https://github.com/commontk/CTK/pull/979#issuecomment-1398636887

Browser thumbnails

---

Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMIndexer.h
Libs/DICOM/Core/ctkDICOMIndexer_p.h

Enabled by default, but settable as a property.
Fixes #1065

ENH: follow symlinks in dicom indexing

---

Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsComboBox.cpp
Libs/Widgets/ctkConsole.cpp
Libs/Widgets/ctkFittedTextBrowser.cpp
Libs/Widgets/ctkMenuComboBox.cpp
Libs/Widgets/ctkMessageBox.cpp
Libs/Widgets/ctkSearchBox.cpp
Libs/Widgets/ctkSettingsDialog.cpp

Qt lupdate tool throws `Cannot invoke tr() like this` warnings when translation function is called using `q->tr(...)`. The problem is that lupdate cannot determine the class name `tr()` is called on and therefore it does not know the translation context. The solution is to spell out the class name in the call, for example `qSlicerScalarVolumeDisplayWidget::tr(...)`. More details are described here: https://github.com/Slicer/SlicerLanguagePacks/blob/main/DevelopersManual.md
see Slicer/SlicerLanguagePacks#17
see Slicer/SlicerLanguagePacks#12

BUG: Fix lupdate warnings on translation function calls

---

Libs/Widgets/Testing/Cpp/ctkDoubleRangeSliderTest1.cpp
Libs/Widgets/Testing/Cpp/ctkRangeWidgetTest.cpp
Libs/Widgets/ctkDoubleRangeSlider.cpp
Libs/Widgets/ctkDoubleSlider.cpp
Libs/Widgets/ctkRangeWidget.cpp
Libs/Widgets/ctkSettingsDialog.h

The minimum and maximum values were not always reachable in ctkDoubleSlider and ctkDoubleRangeSlider widgets when moved the slider to the minimum or maximum position.
For example:
```
lo = -1024
hi = 2000
step = (hi - lo) / 1000.
thresholdSlider = ctk.ctkRangeWidget()
thresholdSlider.spinBoxAlignment = qt.Qt.AlignTop
thresholdSlider.setRange(lo, hi)
thresholdSlider.singleStep = step
thresholdSlider.show()
slider = ctk.ctkDoubleSlider()
slider.minimum = lo
slider.maximum = hi
slider.singleStep = step
slider.show()
slider.connect("valueChanged(double)", lambda v: print(v))
```
The problem was that the integer slider range was determined by rounding, which could result in the integer slider range not covering the entire value range.
Fixed the problem by extending the integer slider range …

BUG: Ensure that the min/max values can be reached in ctkDoubleSlider and ctkDoubleRangeSlider

---

Libs/Scripting/Python/Core/Python/ctk/__init__.py.in
Libs/Scripting/Python/Core/Python/qt/__init__.py.in

Since importing a PythonQt-based module outside of a Qt application leads to a segfault, skip the import if it happens in a standalone python interpreter.
This issue was discovered while working on the following:
* https://github.com/Slicer/Slicer/pull/6876
* https://github.com/Slicer/Slicer/issues/6875
Note that we may revisit this once the integration of the following pull-request has been finalized:
* https://github.com/commontk/CTK/pull/520

Improve ctk & qt python packages to avoid segfault when imported from standalone python

---

Applications/ctkCommandLineModuleExplorer/ctkCmdLineModuleExplorerMainWindow.cpp
Applications/ctkCommandLineModuleExplorer/ctkCmdLineModuleExplorerShowXmlAction.cpp
Applications/ctkCommandLineModuleExplorer/ctkCmdLineModuleExplorerTabList.cpp
Applications/ctkCommandLineModuleExplorer/ctkCmdLineModuleExplorerTreeWidget.cpp
Applications/ctkDICOMHost/ctkDICOMHostMainLogic.cpp
Applications/ctkDICOMObjectViewer/ctkDICOMObjectViewerMain.cpp
Applications/ctkEventBusDemo/ctkEventBusDemoMainWindow.cpp
Applications/ctkExampleHost/ctkHostAppExampleWidget.cpp
Applications/ctkPluginBrowser/ctkPluginBrowser.cpp
Applications/ctkPluginBrowser/ctkPluginTableModel.cpp
Applications/ctkXnatTreeBrowser/ctkXnatTreeBrowserMainWindow.cpp
Libs/DICOM/Widgets/ctkDICOMTableView.cpp
Libs/Widgets/ctkBasePopupWidget.cpp
Plugins/org.commontk.dah.core/ctkDicomAppHostingTypesHelper.cpp
Plugins/org.commontk.eventbus/ctkEventDefinitions.h

see Slicer/SlicerLanguagePacks#17
see Slicer/SlicerLanguagePacks#12

BUG: Mark translatable strings in Applications folder

---

Libs/Widgets/ctkCheckableHeaderView.h
Libs/Widgets/ctkWidgetsPythonQtDecorators.h

`ctkCheckableHeaderView` used to be missing in python #793. 
I modified CTK such that class constructor: `ctkCheckableHeaderView(Qt::Orientation, QWidget *parent)` is now accessible from python. 
Also I moved two overloaded methods `ctkCheckableHeaderView::checkState(...)` to `public Q_SLOTS` so they are now also accessible from python.

Added python bindings for `ctkCheckableHeaderView`

---

Libs/Core/ctkErrorLogAbstractMessageHandler.cpp
Libs/Core/ctkErrorLogAbstractMessageHandler.h
Libs/Core/ctkErrorLogLevel.cpp
Libs/Core/ctkErrorLogLevel.h
Libs/Core/ctkErrorLogQtMessageHandler.cpp
Libs/Core/ctkErrorLogQtMessageHandler.h
Libs/Core/ctkErrorLogTerminalOutput.cpp
Libs/Core/ctkErrorLogTerminalOutput.h
Libs/QtTesting/ctkEventTranslatorPlayerWidget.cpp
Libs/QtTesting/ctkEventTranslatorPlayerWidget.h

CTK objects that only had default constructor (no Object* parameter) were not possible to instantiate in Python:
>>> a=ctk.ctkErrorLogLevel()
Traceback (most recent call last):
File "<console>", line 1, in <module>
ValueError: No constructors available for ctkErrorLogLevel
The issue is fixed by passing arguments of the superclass constructor.
This pull request (along with https://github.com/commontk/CTK/pull/985) supersedes https://github.com/commontk/CTK/pull/796. Accepting arguments in the constructor (that are passed on to the superclass constructor) is a better solution than accepting wrapping of constructors that don't take any arguments.

ENH: Allow instantiation of more CTK objects in Python

---

Libs/Widgets/ctkModalityWidget.cpp
Libs/Widgets/ctkModalityWidget.h

There were several issues with the imaging modality selector widget (ctkModalityWidget):
- when imaging modality abbreviations (CT, MRI, XA, ...) were localized then the widget did not work at all, because the checkbox text was used to identify the checkboxes
- widget state was stored redundantly in SelectedModalities and VisibleModalities variables and the checkbox properties; and these were often inconsistent
Fixed by using Qt object names to identify checkboxes; and removing SelectedModalities and VisibleModalities variables (store widget state in the checkbox properties).

BUG: Fix localization and inconsistent state in ctkModalityWidget

---

Libs/Core/Testing/Cpp/ctkCoreSettingsTest.cpp
Libs/Core/ctkCoreSettings.cpp

Fix cases specifying `<APPLICATION_HOME_DIR>` where relevant.
Add missing unix cases and conditionally include platform specific cases. This is required because the function `QDir::relativeFilePath()` is computes[^1] the path base on `QDir::rootPath()` and `QDir::drives()` that are specific to each operating system.
[^1]: https://github.com/qt/qtbase/blob/5.15/src/corelib/io/qdir.cpp#L844-L897
Also remove unused `d` variables from `ctkCoreSettings`.

Fix ctkCoreSettingsTest

---

Libs/Core/ctkUtils.cpp

This commit fixes `ctkUtilsCopyDirRecursivelyTest1`

Ensure ctk::copyDirRecursively skips hidden file by default

---

Libs/Widgets/Testing/Cpp/ctkDateRangeWidgetTest1.cpp
Libs/Widgets/ctkDateRangeWidget.cpp

Additionally:
* Remove obsolete error message in `ctkDateRangeWidget::displayTime`
* Fix `QDateTime` deprecation warnings in `ctkDateRangeWidgetTest1`
* Simplify handling of Qt4 & Qt5 API differences in `ctkDateRangeWidget`

 Fix regression in ctkDateRangeWidget 

---

Applications/ctkDICOM/Testing/Cpp/ctkDICOMTest1.cpp
Applications/ctkDICOM2/Testing/Cpp/ctkDICOM2Test1.cpp
Applications/ctkDICOMHost/Testing/Cpp/ctkDICOMHostTest1.cpp
Libs/CommandLineModules/Backend/LocalProcess/ctkCmdLineModuleProcessWatcher.cpp
Libs/DICOM/Core/ctkDICOMItem.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMBrowserTest.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMModelTest2.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMServerNodeWidgetTest1.cpp
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/PluginFramework/Testing/org.commontk.pluginfwtest/ctkPluginFrameworkTestSuite.cpp
Libs/PluginFramework/ctkPluginAbstractTracked.tpp
Libs/PluginFramework/ctkPluginAbstractTracked_p.h
Libs/PluginFramework/ctkPluginFramework.cpp
Libs/PluginFramework/ctkPlugin_p.cpp
Libs/Visualization/VTK/Widgets/ctkVTKSurfaceMaterialPropertyWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKSurfaceMaterialPropertyWidget.h
Libs/Widgets/Testing/Cpp/ctkCheckableHeaderViewEventTranslatorPlayerTest1.cpp
Libs/Widgets/Testing/Cpp/ctkCheckableHeaderViewTest1.cpp
Libs/Widgets/Testing/Cpp/ctkCheckableHeaderViewTest2.cpp
Libs/Widgets/Testing/Cpp/ctkCheckableModelHelperTest1.cpp
Libs/Widgets/Testing/Cpp/ctkCheckableModelHelperTest2.cpp
Libs/Widgets/Testing/Cpp/ctkCoordinatesWidgetValueProxyTest.cpp
Libs/Widgets/ctkCheckableComboBoxEventTranslator.cpp
Libs/Widgets/ctkFlowLayout.cpp
Libs/Widgets/ctkMaterialPropertyWidget.cpp
Libs/Widgets/ctkTransferFunctionView.cpp
Libs/Widgets/ctkTreeComboBox.cpp
Plugins/org.commontk.configadmin/ctkConfigurationAdminImpl.cpp
Plugins/org.commontk.configadmin/ctkConfigurationStore.cpp

These fixes are confirmed to build with all CTK options enabled for both Qt4 and Qt5

Fix warnings

---

Libs/Widgets/Resources/UI/ctkErrorLogWidget.ui
Libs/Widgets/ctkErrorLogWidget.cpp
Libs/Widgets/ctkErrorLogWidget.h

Needed by https://github.com/Slicer/Slicer/pull/7059

ENH: Add layout orientation to ErrorLogDockWidget

---

Libs/PluginFramework/ctkPluginActivator.h
Libs/Widgets/ctkIconEnginePlugin_qt5.h

Also update `ctkPluginActivator.h` docstring to document use of `Q_PLUGIN_METADATA`

DOC: Remove obsolete references to Q_EXPORT_PLUGIN2 specific to Qt4

---

CMakeExternals/Log4Qt.cmake
CMakeLists.txt
Plugins/org.commontk.log4qt/ctkLog4QtPlugin.cpp

This is a follow-up of d6f12b0 (`Make more libs and apps compatible with Qt5.`) where the plugin was originally removed from the set of plugins available when building against Qt5.

BUG: Re-enable support for "org.commontk.log4qt" plugin with Qt5

---

CMakeLists.txt

This commit is a follow-up of d6f12b003 (Make more libs and apps compatible with Qt5.) where the application was originally excluded.

ENH: Re-enable support for building ctkQtTesting example app with Qt5

---

CMakeLists.txt
Libs/CommandLineModules/Core/ctkCmdLineModuleParameter.h
Libs/Core/ctkCallback.h
Libs/Core/ctkErrorLogAbstractModel.h
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest4.cpp
Libs/PluginFramework/Testing/org.commontk.eventadmintest/ctkEAScenario1TestSuite.cpp
Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp
Libs/Scripting/Python/Core/ctkAbstractPythonManager.h
Libs/Widgets/ctkComboBox.cpp
Libs/Widgets/ctkConsole.cpp
Libs/Widgets/ctkCoordinatesWidget.h
Libs/Widgets/ctkDoubleSpinBox.h
Libs/Widgets/ctkFlowLayout.h
Libs/Widgets/ctkLayoutManager.h
Libs/Widgets/ctkPathLineEdit.h
Libs/XNAT/Core/ctkXnatDataModel.h
Libs/XNAT/Core/ctkXnatSession.h

Typos in `CMakeLists.txt` (`qmlrpc` -> `qxmlrpc`) was introduced in 4f6262c4 (`DOC: Add comment documenting why the "eventbus" plugin is disabled with Qt5`) and identified while inspecting the file.
Remaining of typos were identified and/or fixed using codespell using the following script:
```bash
python3 -m venv /tmp/codespell
source /tmp/codespell-venv/bin/activate
pip install codespell
echo "comunication
currentry
fwe
dependees
invokable
maked
numer
noe
objekt
ot
requestor
ser
serie
statics
ta
te
to
ue" > /tmp/.codespellignore
codespell -I /tmp/.codespellignore -$(fd -e h -e hpp -e cpp -e txt -e dox -e cmake)
codespell -I /tmp/.codespellignore -w -$(fd -e h -e hpp -e cpp -e txt -e dox -e cmake)
```

DOC: Fix typos

---

Libs/Core/ctkCompilerDetections_p.h
Libs/Core/ctkErrorLogAbstractModel.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Core/ctkDICOMDisplayedFieldGenerator.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRuleFactory.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRuleFactory.h
Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Widgets/ctkDICOMQueryRetrieveWidget.cpp
Libs/DICOM/Widgets/ctkDICOMTableView.cpp
Libs/Visualization/VTK/Core/ctkVTKScalarsToColorsUtils.cpp
Libs/Visualization/VTK/Core/vtkDiscretizableColorTransferChart.cpp
Libs/Visualization/VTK/Core/vtkScalarsToColorsContextItem.cpp
Libs/Visualization/VTK/Core/vtkScalarsToColorsPreviewChart.cpp
Libs/Visualization/VTK/Widgets/Testing/Cpp/ctkVTKScalarsToColorsComboBoxTest1.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.h
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsComboBox.cpp

This commit replaces occurrences of the `CTK_NULLPTR` macro with `nullptr`.
This one-liner was used to perform the update:
```
git grep -l "CTK_NULLPTR" | fgrep -v CMakeLists.txt | fgrep -v .cmake | xargs sed -i '' -e "s/CTK_NULLPTR/nullptr/g"
```
Adapted from Slicer/Slicer@015d346b9 (`STYLE: Replace ITK_NULLPTR with nullptr`)

STYLE: Remove obsolete CTK_NULLPTR macro not needed with C++ >= 11

---

Libs/DICOM/Core/ctkDICOMIndexer.cpp

This commit reverts 7bb0d9fdb (`COMP: Fix Qt4/C++98 ctkDICOMIndexerPrivate build using literal signal/slot`)
This addresses the following error reported when running ctkDICOMIndexerTest1:
```
QObject::connect: No such signal QThread::"finished()"
QObject::connect: No such signal ctkDICOMIndexerPrivate::"startWorker()"
QObject::connect: No such signal ctkDICOMIndexerPrivateWorker::"progress(int)"
QObject::connect: No such signal ctkDICOMIndexerPrivateWorker::"progressDetail(QString)"
QObject::connect: No such signal ctkDICOMIndexerPrivateWorker::"progressStep(QString)"
QObject::connect: No such signal ctkDICOMIndexerPrivateWorker::"updatingDatabase(bool)"
QObject::connect: No such signal ctkDICOMIndexerPrivateWorker::"indexingComplete(int,int,int,int)"
QObject::connect: No such signal …
```

BUG: Fix ctkDICOMIndexer reverting back to functor signal/slot

---

Libs/Widgets/ctkFlowLayout.cpp

This commit fixes a regression introduced in e66324212 (`COMP: Fix deprecated warning related to QWidget::getContentsMargins()`).
Since functions `QWidget::contentsRect()` and `QWidget::contentsMargins()` are not equivalent, the logic associated with `ctkFlowLayout::minimumSize()` and `ctkFlowLayout::sizeHint()` was incorrect.
Fixes https://github.com/Slicer/Slicer/issues/7108
Reported by @cpinter

BUG: Fix ctkFlowLayout regression related to minimum size computation

---

Libs/Widgets/ctkRangeSlider.cpp

Note: I'm using latest 3D Slicer for testing the implementation of these changes.
cc: @sjh26 since you also mentioned dealing with customization of this widget
```python
window_level = slicer.qMRMLWindowLevelWidget()
window_level.show()
```
Then upon applying a customization for the disabled color of Sliders, there is no observed change
```python
stylesheet = "QSlider:disabled {selection-background-color: green;}"  # green for visibility of this example
slicer.app.setStyleSheet(stylesheet)
```
By default the slider appears in a (more correct) disabled state look
```python
window_level = slicer.qMRMLWindowLevelWidget()
window_level.show()
```
Then upon applying a customization for the disabled color of Sliders, you can actually observe a change
```python
stylesheet = "QSlider:disabled …
```

ctkRangeSlider customization 

---

CMake/ctkListToString.cmake

This addresses the following warning:
```
CMake Deprecation Warning at CMake/ctkListToString.cmake:24 (cmake_policy):
The OLD behavior for policy CMP0007 will be removed from a future version
of CMake.
The cmake-policies(7) manual explains that the OLD behaviors of all
policies are deprecated and that a policy should be set to OLD only under
specific short-term circumstances.  Projects should be ported to the NEW
behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
CMake/ctkMacroSetupQt.cmake:158 (ctk_list_to_string)
CMakeLists.txt:421 (ctkMacroSetupQt)
```
The `string(JOIN ...)` sub-command was introduced in CMake 3.12.
See https://cmake.org/cmake/help/v3.27/command/string.html#join

COMP: Update ctk_list_to_string to use CMake join implementation if available

---

CMake/ctkMacroSetupQt.cmake

For example:
```
$ cmake .
[...]
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, XmlPatterns, Concurrent, Sql, Test, Multimedia, Widgets, OpenGL, UiTools, WebEngineWidgets, Script)
[...]
```

ENH: Display Qt version and Qt components used to configure CTK

---

CMake/ctkMacroSetupQt.cmake

This update was done based on the output of the process documented on the CTK wiki page "Maintenance / Updates of Required Qt Components". See https://github.com/commontk/CTK/wiki/Maintenance#updates-of-required-qt-components
See before/after when configuration CTK with default options
Before:
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, XmlPatterns, Concurrent, Sql, Test, Multimedia)
```
After:
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Test)
```
_Output based of Slicer/Slicer@77f1e2d06c_
Before:
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, XmlPatterns, Concurrent, Sql, Test, Multimedia, Widgets, OpenGL, UiTools)
```
After:
```
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Xml, Sql, Multimedia, Widgets, OpenGL, UiTools, …
```

ENH: Improve setting of CTK_QT5_COMPONENTS based on actual requirements

---

CMake/ctkMacroSetupQt.cmake

This commit fixes a regression introduced in c0c8e41db (ENH: Improve setting of CTK_QT5_COMPONENTS based on actual requirements) adding XmlPatterns as a requirement if CTK_LIB_QtTesting is enabled.

COMP: Fix CTK QtTesting library build

---

CMake/ctkMacroCheckExternalProjectDependency.cmake

```
$ git shortlog ea920eb..dff357a --no-merges
Jean-Christophe Fillion-Robin (5):
ci: Add GitHub Actions based workflow
ci: Exclude "IncludeDependencies-DifferentGenerator-Test" with CMake 2.8.x
DOC: Update README adding GitHub Actions badge
ci: cancel in-progress GitHub Actions workflow on repeated pushes
ExternalProjectDependency: Set DOWNLOAD_EXTRACT_TIMESTAMP to 1 if CMake >= 3.24
```

ENH: Update ExternalProjectDependency based on commontk/Artichoke@dff357a

---

CMake/ctkMacroSetupQt.cmake

Follow-up c0c8e41db (`ENH: Improve setting of CTK_QT5_COMPONENTS based on actual requirements`) fixing the check adding Sql to the list of components when `CTK_ENABLE_PluginFramework`
```
$ cmake \
-DCTK_ENABLE_PluginFramework:BOOL=ON \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DQt5_DIR:PATH=$Qt5_DIR -DCTK_QT_VERSION:STRING=5 \
../CTK
[...]
-- Configuring CTK with Qt 5.15.2 (using modules: Core, Concurrent, Test, Designer)
-- SuperBuild - First pass
-- SuperBuild - First pass - done
[...]
-- SuperBuild - CTK[OK]
-- Configuring done (2.9s)
-- Generating done (0.0s)
```
```
$ rm -rf *
$ cmake \
-DCTK_ENABLE_PluginFramework:BOOL=ON \
-DCMAKE_BUILD_TYPE:STRING=Release \
-DQt5_DIR:PATH=$Qt5_DIR -DCTK_QT_VERSION:STRING=5 \
../CTK
[...]
-- Configuring CTK with Qt 5.15.2 (using modules: Core, …
```

COMP: Fix CTK PluginFramework library build

---

CMake/ctkMacroSetupQt.cmake
CMakeLists.txt

Address a regression introduced in a0e74a080 (COMP: Update CMake files removing support for Qt 4.x) by fixing the following error reported when configuring without explicitly setting `CTK_QT_VERSION`:
```
cmake \
-DQt5_DIR:PATH=$Qt5_DIR \
-DCMAKE_BUILD_TYPE:STRING=Release \
../CTK
[...]
-- Checking if --no-as-needed linker flag is required - no
-- CTK_LIB_Core_WITH_BFD_SHARED is OFF
-- CTK_LIB_Core_WITH_BFD_STATIC is OFF
CMake Error at Libs/Visualization/VTK/Widgets/target_libraries.cmake:15 (message):
Support for this Qt is not implemented
Call Stack (most recent call first):
CMake/ctkMacroTargetLibraries.cmake:131 (include)
CMake/ctkFunctionGenerateDGraphInput.cmake:78 (ctkFunctionCollectTargetLibraryNames)
CMakeLists.txt:844 (ctkFunctionGenerateDGraphInput)
[...]
```

COMP: Fix configuration without explicitly setting CTK_QT_VERSION

---

CMake/ctkLinkerAsNeededFlagCheck/CMakeLists.txt

Starting with CMake 2.26, a warning is reported if "cmake_minimum_required()" is not called before the "project()" command.
See https://cmake.org/cmake/help/v3.26/release/3.26.html#other-changes
It fixes the following warning:
```
CMake Warning (dev) at /path/to/CTK/CMake/ctkLinkerAsNeededFlagCheck/CMakeLists.txt:1 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
Adapted from Slicer/Slicer@968fd241328d3a7b6d5fe632b32db863aabcf90c introduced through:
* https://github.com/Slicer/Slicer/pull/7135

COMP: Fix CMake 3.26 warning in ctkLinkerAsNeededFlagCheck project

---

Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKAbstractView_p.h
Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKRenderView.h
Libs/Visualization/VTK/Widgets/ctkVTKRenderView_p.h
Libs/Visualization/VTK/Widgets/ctkVTKSliceView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKSliceView.h
Libs/Visualization/VTK/Widgets/ctkVTKSliceView_p.h

Add protected constructor to `ctkVTKRenderView` and `ctkVTKSliceView` for associating a derived pimpl.
This is required to have the complete virtual function chain executed when virtual function are called in the pimpl `init()` function.
While I confirmed that building Slicer against this change did not require any additional changes, it will be allow to move forward with the integration of `ENH: Allow virtual func to be called during MRML(ThreeD|Slice)View pimpl`[^1]
[^1]: https://github.com/Slicer/Slicer/pull/7311/commits/dca4f5dd541c5320ba5900f1a6c034c4cd19ee02

Ensure virtual functions can be called from derived ctkVTK view pimpl

---

Libs/DICOM/Core/Resources/dicom-schema.sql
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h
Libs/DICOM/Core/ctkDICOMDatabase_p.h
Libs/DICOM/Core/ctkDICOMItem.cpp

This generalizes the ctkDICOMDatabase code to ease hard-coded restrictions about DICOM files always being on disk.  Now the schema includes a `URL` field of the SQLite database so certain file-specific operations are only performed on filePaths while URL are handled independently.  Entries in the `Images` table of the database may now have either a `URL` or a `fileName` or both and new accessors are provided to get `URL`s at the series and instance level.
Also this contains a fix to the ctkDICOMTagCache so that tags are always stored internally as uppercase hex, so a string like "0010,000d" will always be turned into "0010,000D" for storage in the database.  Both forms can be used to query tags.  This avoids the situation where some cache entries were duplicated because different code …

ENH: Virtualize DICOM database

---

CMake/ctkMacroBuildLibWrapper.cmake
CMake/ctkMacroWrapPythonQtModuleInit.cpp.in
CMake/ctk_compile_python_scripts.cmake.in
CMakeExternals/VTK.cmake
Libs/Scripting/Python/Core/Testing/Cpp/ctkAbstractPythonManagerTest.cpp
Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp
Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp

Following 777b5ea (`DOC: Mention Qt 4/C++98/Python 2.7/VTK 8/ITK v4.13.3 are unsupported`), support for Python 2.7 is obsolete.

Remove Python 2.x support

---

Applications/ctkDICOMDemoSCU/Testing/Cpp/ctkDICOMDemoSCUTest1.cpp
Applications/ctkDICOMQuery/ctkDICOMQueryMain.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest2.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMAppWidgetTest1.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMBrowserTest.cpp
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp
Libs/DICOM/Widgets/ctkDICOMServerNodeWidget.cpp
Libs/Widgets/ctkFileDialog.cpp

Ensure the following tests can be executed after installing CTK into `<CTK-top-level-build>/CMakeExternals/Install/`:
* `ctkDICOMAppWidgetTest1`
* `ctkDICOMDatabaseTest2`
* `ctkDICOMBrowserTester`
It also updates `ctkFileDialog` to ensure it considers application attribute `AA_DontUseNativeDialogs`.

Fix DICOM tests and update `ctkFileDialog` to consider  `AA_DontUseNativeDialogs` attribute

---

Applications/ctkDICOMHost/Testing/Cpp/CMakeLists.txt
Applications/ctkDICOMHost/Testing/Cpp/ctkDICOMHostTest1.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest1.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest2.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest3.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest4.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest5.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest6.cpp
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest7.cpp
Libs/DICOM/Core/ctkDICOMTester.cpp

* Update `ctkDICOMTester` to lookup DCMTK executables in build tree. This removes the requirement to install CTK into the `CMakeExternals/Install` directory. 
* Support running `ctkDICOMHostTest1` without having to install CTK 
* Support running `ctkDICOMDatabase` tests in parallel using `QTemporaryDir` introduced in Qt5

Simplify DICOM testing removing needs for installing CTK

---

.github/workflows/lint.yml
.pre-commit-config.yaml

This pull-request adds workflow leveraging pre-commit, a framework for managing and maintaining pre-commit hooks.
> [!IMPORTANT]
> For now, this will only report info to developers after the PR is submitted. There are no changes in the hook setup locally yet.
See https://pre-commit.com/ and https://github.com/pre-commit/action
Running the pre-commit locally can be done using the following
command:
```
pre-commit run --all-files
```
The hooks enabled in the "pre-commit-config.yaml" configuration
file are:
* `check-added-large-files`
Prevent giant files from being committed.
Set the size to 1024 to match the value hard-coded in
https://github.com/Slicer/Slicer/blob/hooks/pre-commit#L125
* `check-case-conflict`
Check for files with names that would conflict on a case-insensitive
filesystem …

ENH: Add GitHub Actions workflow for running "pre-commit"

---

Libs/Core/Testing/Cpp/ctkCoreSettingsTest.cpp

Follow-up on commit f0bb5d782 (ENH: Allow saving relative paths to settings) where the test case was incorrectly specified.
It fixes the following error:
```
10: FAIL!  : ctkCoreSettingsTester::testMultiplePaths(windows-style absolute paths) Compared lists differ at index 0.
10:    Actual   (settings.value(key).toStringList()): "d:/windows/path/internal/dir"
10:    Expected (expectedStoredValues): "<APPLICATION_HOME_DIR>/internal/dir"
10: C:\path\to\CTK\Libs\Core\Testing\Cpp\ctkCoreSettingsTest.cpp(115) : failure location
```

BUG: Fix ctkCoreSettingsTest testMultiplePaths on Windows

---

Libs/Widgets/Testing/Cpp/ctkSettingsPanelTest.cpp

This ensures newlines are always read as `/n` independently of the platform.
It fixes errors like the following:
```
126: FAIL!  : ctkSettingsPanelTester::testChangeProperty(null none changed obj) Compared values are not the same
126:    Actual   (currentSettingContent)             : "[General]\r\nproperty=2\r\n"
```

BUG: Fix ctkSettingsPanelTest reading settings file as text

---

Libs/Widgets/Testing/Cpp/ctkSettingsPanelTest1.cpp
Libs/Widgets/ctkSettingsPanel.cpp

This issue was discovered while working on fixing `ctkSettingsPanelTest1` failure.
Further improve the fix integrated in c8ce0dec ("BUG: Fix incorrect changed settings indicator", 2018-07-04) and update ctkSettingsPanelTest1 accordingly.
cc: @jamesobutler

BUG: Fix applySettings() to emit "settingChanged()" only if needed

---

Libs/DICOM/Core/Testing/Cpp/CMakeLists.txt
Libs/DICOM/Core/Testing/Cpp/ctkDICOMDatabaseTest6.cpp
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h

This is a follow-up of https://github.com/commontk/CTK/pull/1164 intended to fix https://github.com/Slicer/Slicer/issues/7290
References:
* https://github.com/commontk/CTK/pull/1164
* https://github.com/Slicer/Slicer/issues/7290

ENH: Add removePatient/Series/Study signals to DICOM database

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp

Fix https://github.com/commontk/CTK/issues/1186

ENH: Remove unnecessary logging information from ctkDICOMDatabase class

---

CMakeExternals/PythonQt.cmake

Meticulous backport of all recent changes introduced in https://github.com/MeVisLab/pythonqt/
Commit impacting only the PythonQt library are prefix with `[Backport]` the one impacting only the generator are prefixed with `[Backport generator]`.
List of PythonQt changes:
```
$ git shortlog c4a5a155b..db525aff0 --no-merges
Christophe Giboudeaux (1):
[Backport] Fix build with Python 3.8
David Brooks (2):
[Backport] Use `quote` characters around includes of our headers.
[Backport] Support Qt 5.12
Felix Petriconi (4):
[Backport generator] Also generate python function for operator!=()
[Backport generator] Default initialize all members
[Backport] Replace foreach macro with range based for loop
[Backport generator] Remove __* and _Uppercase from symbols because they must not been used
Gregor …
```

ENH: Update PythonQt backporting recent changes from `MeVisLab/pythonqt`

---

CMake/ctk_compile_python_scripts.cmake.in

Refine the script introduced in commit db3f4d99 ("Re-create python compile script only if needed and fix dependency. See #449", 2014-04-16) by explicitly specifying the `cfile` parameter. Disable the default behavior (introduced in Python 3.2) of generating .pyc files in the `__pycache__` directory, as outlined in PEP-3147.
This improvement is needed for Slicer-based applications, enabling them to locate scripted modules and plugins as either .py or .pyc files in a specific directory.
References:
* PEP-3147: https://peps.python.org/pep-3147/
* Slicer Forum Discussion: https://discourse.slicer.org/t/how-to-hide-the-code-of-the-script-module/26135/14
* Python Documentation: https://docs.python.org/3/library/py_compile.html#py_compile.compile

ENH: Always compile python scripts as legacy .pyc files

---

Libs/Core/ctkJobScheduler.cpp
Libs/DICOM/Widgets/ctkDICOMVisualBrowserWidget.cpp

One of the DICOM widgets crashed the Qt designer because ctkDICOMScheduler::~ctkDICOMScheduler() called ctkJobScheduler::waitForDone, and that method called processEvents(). After returning form processEvents() the application crashed because the "this" pointer has become invalid (probably the ctkDICOMScheduler object got deleted).
Solved the issue by removing processEvents() from ctkJobScheduler::waitForDone, and instead calling processEvents() before calling ctkJobScheduler::waitForDone.
@Punzo please have a look and feel free to suggest a better design.

BUG: Fix Qt designer crash at startup

---

Libs/Scripting/Python/Core/ctkAbstractPythonManager.h

Follow-up of fc58c6a16 (ENH: Make executeString and executeFile invokable from Python)

ENH: Support using ctkAbstractPythonManager::ExecuteStringMode from Python

---

CMake/ctkMacroSetupQt.cmake
CMakeLists.txt
Utilities/DGraph/CMakeLists.txt

Avoids configure errors with the latest ITK and CMake 3.29.3:
```log
6>CMake Warning (dev) at M:/a/Srd/ITK-build/ITKConfig.cmake:90 (if):
6>  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
6>  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
6>  set the policy and suppress this warning.
6>
6>  IN_LIST will be interpreted as an operator when the policy is set to NEW.
6>  Since the policy is not set the OLD behavior will be used.
6>Call Stack (most recent call first):
6>  Libs/ImageProcessing/ITK/Core/CMakeLists.txt:16 (find_package)
6>This warning is for project developers.  Use -Wno-dev to suppress it.
6>
6>CMake Error at M:/a/Srd/ITK-build/ITKConfig.cmake:90 (if):
6>  if given arguments:
6>
6>    "ITK_FIND_REQUIRED_ITKCommon" "OR" "M" …
```

ENH: Increase minimum required CMake version to 3.16.3

---

Libs/DICOM/Widgets/ctkDICOMJobListWidget.cpp
Libs/DICOM/Widgets/ctkDICOMPatientItemWidget.cpp
Libs/DICOM/Widgets/ctkDICOMStudyItemWidget.cpp

tr() function was not used correctly at a handful of places.

BUG: Fix translations in DICOM widgets

---

Libs/Widgets/ctkDoubleSpinBox.cpp
Libs/Widgets/ctkDoubleSpinBox.h
Libs/Widgets/ctkDoubleSpinBox_p.h
Libs/Widgets/ctkSliderWidget.cpp
Libs/Widgets/ctkSliderWidget.h

New method is added to ctkDoubleSpinBox and ctkSliderWidget to check if a value is currently being set using the spinbox. This is useful because when there are many sibling widgets then many signals may be emitted and it may be difficult to determine which widget was the source of all changes.
This feature was needed for fixing https://github.com/Slicer/Slicer/issues/7574

ENH: Add method to check if double-spinbox value is being edited

---

Libs/Core/ctkErrorLogAbstractModel.cpp
Libs/Core/ctkErrorLogLevel.h

Fix regression introduced in https://github.com/commontk/CTK/commit/e9ef4c397b49bd594bf75f3be80a516252cc410b
which made the error filtering buttons bugged.

BUG: Fix error log filtering in ctkErrorLogWidget

---

CMakeExternals/DCMTK.cmake

Backport security fixes from the following post https://forum.dcmtk.org/viewtopic.php?t=5192 because of the following CVE:
* [CVE-2022-2119](https://www.cvedetails.com/cve/CVE-2022-2119/)
* [CVE-2022-2120](https://www.cvedetails.com/cve/CVE-2022-2120/)
List of DCMTK changes:
```
$ git shortlog 0f9bf4d9e..11972eaa4 --no-merges
Marco Eichelberg (2):
[Backport] Fixed possible NULL pointer dereference.
[Backport] Fixed path traversal vulnerability.
```
Related pull requests & issues:
* https://github.com/commontk/DCMTK/pull/14

BUG: Update DCMTK to backport fixes for CVE-2022-2119 and CVE-2022-2120

---

Libs/DICOM/Core/CMakeLists.txt
Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMThumbnailGenerator.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMImageTest1.cpp
Libs/DICOM/Widgets/Testing/Cpp/ctkDICOMItemViewTest1.cpp

Introduces two compatibility updates for DCMTK integration:
1. **Explicit `QByteArray` Conversion for DCMTK Compatibility**: Adds an explicit conversion from `QByteArray` to `const char *`, preparing for changes in DCMTK's handling of the `filename` parameter (commit DCMTK/dcmtk@1ebac2d0f).
2. **Support for Namespaced DCMTK CMake Targets**: Adapts the build system to support namespaced CMake targets introduced in DCMTK commit DCMTK/dcmtk@c684bb3. The update correctly sets the `KIT_target_libraries` variable to accommodate the "DCMTK::" prefix in target names.
Related pull requests:
* https://github.com/Slicer/Slicer/pull/6709
* https://github.com/InsightSoftwareConsortium/ITK/pull/4910
* https://github.com/commontk/CTK/pull/1053

Support building against DCMTK >= 3.6.7

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp
Libs/DICOM/Core/ctkDICOMDatabase.h

Recent 88ff72b9c2b1e57cf4f822ea2e547be5b9a32b98 commit changed `ctkDICOMDatabase::fileValue` behavior so that it no longer returns DICOM tag value for files that are not already in the database. This is an issue because this method has been used universally for any DICOM files (it returned result faster for files that are cached in the DICOM database but it worked for files not in the database, too).
This commit restores the previous, preferred behavior.

BUG: Fix ctkDICOMDatabase::fileValue for non-cached files

---

Libs/Scripting/Python/Core/ctkAbstractPythonManager.cpp
Libs/Scripting/Python/Core/ctkAbstractPythonManager.h

This pull request includes a series of improvements and bug fixes to the `ctkAbstractPythonManager::pythonAttributes` and related methods improving the autocompletion model. The changes focus on simplifying the code, improving memory management, and ensuring more accurate and error-resilient behavior when inspecting Python objects.
- <s>Exclude property-like accessors from autocompletion</s>
- Fix reference management for `classToInstantiate`
- Improve error handling during attribute lookup
- Simplify logic by removing unused `dict` variable
Related pull request:
* https://github.com/Slicer/Slicer/pull/8238

 Improve robustness of Python completion model

---

Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.h

This commit adds the option to set the current component in ctkVTKVolumePropertyWidget, allowing editing of components other than the first one.

ENH: Add option to set current component in ctkVTKVolumePropertyWidget

---

Libs/Visualization/VTK/Widgets/ctkVTKChartView.cpp

This fixes the following observed build error when building with VTK 9.5.0.rc1.
```
'<function-style-cast>': cannot convert from 'vtkStdString' to 'QString'
```

COMP: Fix build error with VTK 9.5

---

CMake/ctkLinkerAsNeededFlagCheck/CMakeLists.txt

Ensure consistent use of the updated CMake minimum version across all configuration checks to support future compatibility with CMake 4.
This follows up on commit e081be7d ("ENH: Increase minimum required CMake version to 3.16.3", 2024-05-30) by updating the `cmake_minimum_required()` call in `ctkLinkerAsNeededFlagCheck` to match the project-wide baseline.
<details><summary>Previous description</summary>
<p>
ENH: Support compilation with CMake 4+ 
Set the cmake_minimum_required version to the same value as the reset of the CTK package to allow building this small package for testing.
</p>
</details>

COMP: Support build using CMake 4+ by consistently requiring CMake 3.16.3

---

CMakeExternals/PythonQt.cmake

This follows the plan mentioned in https://github.com/commontk/CTK/pull/1238#issuecomment-3029264024 where CTK would switch from the `patched-9` branch of PythonQt to the `patched-v3.6.1-2025-06-13-a2687828e` branch. It is based off https://github.com/MeVisLab/pythonqt/releases/tag/v3.6.1 with minimal additional commits added on top. The previous "patched-9" based branch was based on a very old version with a large collection of manual backports.
This is ultimately a continuation of https://github.com/commontk/CTK/pull/1159 and https://github.com/Slicer/Slicer/pull/7475 which also attempted to update to a newer PythonQt base. This branch includes Qt 5.15 wrappers unlike the older branch. Reviewing https://doc.qt.io/qt-5/newclasses515.html#new-enum-types, this now allows me to use …

COMP: Update PythonQt to branch based off upstream v3.6.1

---

Libs/Widgets/ctkDirectoryButton.cpp

Avoids direct QDir object assignments in `ctkDirectoryButton`, using `setPath()` instead for improved compatibility and clarity.

COMP: Replace QDir assignment with setPath()

---

Libs/DICOM/Widgets/ctkDICOMMetadataDialog.cpp

This improves usability by making the ctkDICOMMetadataDialog non-modal. It allows users to debug and compare metadata more easily without disrupting their workflow.

ENH: Set ctkDICOMMetadataDialog as non-modal window

---

Libs/Visualization/VTK/Widgets/ctkVTKAbstractView.cpp

On some computers, VTK views were not updating until the mouse was moved on the screen. This was due to Qt not repainting the view after the VTK rendering was completed, because the widget was not scheduled for repaint.
fixes https://github.com/Slicer/Slicer/issues/7206

BUG: Fixed VTK views not updating

---

Libs/Widgets/ctkQImageView.cpp

- Also fixes a warning/error depending on the build settings
--- 
_Description updated by @jcfr_
This pull request addresses a regression in `ctkQImageView` where the spacing string was not being formatted correctly. The issue was introduced in a previous commit (e6d44f8a) while marking strings translatable. The patch ensures that `QString::number` is called with the correct arguments to format the spacing  values properly.

BUG: Fix display of spacing string in ctkQImageView

---

CMake/ctkMacroCheckExternalProjectDependency.cmake

This changes ensures BUILD_JOB_SERVER_AWARE option is set on each external projects for CMake >= 3.28 and above. It addresses the `gmake[N]: *** read jobs pipe: Bad file descriptor.` issue associated with the build command.
```
$ git shortlog dff357a..00601c2 --no-merges
Jean-Christophe Fillion-Robin (19):
style: Fix typos identified using codespell
ci: Add "codespell" GitHub Actions workflow
ci: Update CI workflow runner from ubuntu-20.04 to ubuntu-22.04
ci: Update CI workflow to test newer CMake versions >= 3.28.x
ci: Ensure all jobs run independently of failure
ci: Update CI workflow to report installed CMake version
ci: Fix ctest execution for CMake >= 3.30 passing an empty string as label to exclude
ci: Support testing using CMake >= 4.0
ci: Update CI workflow …
```

ENH: Update ExternalProjectDependency based on commontk/Artichoke@00601c2
