commontk/CTK

Libs/Visualization/VTK/Widgets/ctkVTKHistogram.cpp
Libs/Visualization/VTK/Widgets/ctkVTKHistogram.h
Libs/Widgets/ctkWidgetsPythonQtDecorators.h

@ayarmarkovich Please test and let us know how it works.

Improve ctkVTKHistogram metaobject for better pythonqt wrapping

---

Libs/PluginFramework/ctkPluginAbstractTracked.tpp
Libs/PluginFramework/ctkPluginAbstractTracked_p.h
Libs/PluginFramework/ctkPluginTracker.tpp
Libs/PluginFramework/ctkPluginTracker_p.h
Libs/PluginFramework/ctkPluginTracker_p.tpp
Libs/PluginFramework/ctkServiceTracker.tpp
Libs/PluginFramework/ctkServiceTracker_p.h
Libs/PluginFramework/ctkServiceTracker_p.tpp
Libs/PluginFramework/ctkTrackedPlugin.tpp
Libs/PluginFramework/ctkTrackedService.tpp
Libs/PluginFramework/service/debug/ctkDebugOptionsListener.h

Signed-off-by: Rostislav Khlebnikov <r.khlebnikov@gmail.com>

DEBUG variable renamed to DEBUG_FLAG

---

Libs/XNAT/Core/Testing/ctkXnatSessionTest.cpp
Libs/XNAT/Core/ctkXnatExperiment.cpp
Libs/XNAT/Core/ctkXnatObject.cpp
Libs/XNAT/Core/ctkXnatResource.cpp
Libs/XNAT/Core/ctkXnatSubject.cpp

This pull request replaces pull request #574
Cleaned up commit message and create integration branch for master merge.

xnat resource uri with name integration

---

Libs/Widgets/Testing/Cpp/ctkAxesWidgetTest1.cpp
Libs/Widgets/ctkAxesWidget.cpp
Libs/Widgets/ctkAxesWidget.h

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

ENH: ctkWidgetAxes: Add setter for AxisLabels

---

Libs/DICOM/Widgets/ctkDICOMObjectModel.h

This commit fixes a regression introduced in d8bbc43 (Fix some Qt5
component issues)

Fix ctkDICOMObjectModel build error

---

Applications/ctkSimplePythonShell/Testing/Python/ctkWidgetsTest.py
Applications/ctkSimplePythonShell/ctkSimplePythonShellMain.cpp
Libs/Scripting/Python/Core/ctkAbstractPythonManager.h

This allows creating variables in the Python console's scope.

ENH: Make executeString and executeFile invokable from Python

---

Libs/Visualization/VTK/Widgets/ctkVTKRenderView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKRenderView.h
Libs/Visualization/VTK/Widgets/ctkVTKRenderView_p.h

Also improved documentation of a few members of the class.

ENH: Allow automatic view rotation by less than 1 degree

---

Libs/Core/ctkBackTrace.cpp
Libs/Widgets/ctkPathLineEdit.cpp
Libs/Widgets/ctkPathLineEdit.h

* explicits type conversion.
* use of tr().
* removes duplicate Q_PROPERTY (regression from 70ea952)

Fixes warnings.

---

Libs/Visualization/VTK/Core/CMakeLists.txt

BUG: Missing vtkRenderingFreeType library option

---

CMakeExternals/QtTesting.cmake
Libs/QtTesting/ctkXMLEventObserver.cpp
Libs/QtTesting/ctkXMLEventObserver.h
Libs/QtTesting/ctkXMLEventSource.cpp
Libs/QtTesting/ctkXMLEventSource.h
Libs/Visualization/VTK/Widgets/Testing/Cpp/CMakeLists.txt

No test fail due to the change.

Increment QtTesting version

---

CMakeLists.txt

COMP: Setting CMP0020 to NEW

---

CMake/CircleCI/CircleCI_CTK_Docker.cmake
Libs/Core/Testing/Cpp/ctkAbstractFactoryTest1.cpp
Libs/Widgets/CMakeLists.txt
Libs/Widgets/Testing/Cpp/CMakeLists.txt
Libs/Widgets/Testing/Cpp/ctkCrosshairLabelTest2.cpp
Libs/Widgets/Testing/Cpp/ctkErrorLogQtMessageHandlerWithThreadsTest1.cpp
Libs/Widgets/Testing/Cpp/ctkLanguageComboBoxTest.cpp
Libs/Widgets/Testing/Cpp/ctkScreenshotDialogTest1.cpp
Libs/Widgets/Testing/Cpp/ctkWidgetsTestingUtilitiesTest.cpp
Libs/Widgets/ctkDoubleSpinBox.h
Libs/Widgets/ctkDoubleSpinBox_p.h
Libs/Widgets/ctkWidgetsTestingUtilities.cpp
Libs/Widgets/ctkWidgetsTestingUtilities.h

Set `CTK_ENABLE_Widgets` to test widgets on CI.

Test widgets on CI

---

Libs/Core/ctkBooleanMapper.cpp
Libs/Core/ctkBooleanMapper.h
Libs/Core/ctkCorePythonQtDecorators.h
Libs/Widgets/ctkComboBox.cpp
Libs/Widgets/ctkComboBox.h

Python usability of ctkBooleanMapper (thanks @jcfr!)
ctkComboBox supports definition of settings values for each choice through user data

Settings related improvements

---

CMake/CircleCI/CircleCI_CTK_Docker.cmake

ci: Exclude failing test "ctkWidgetsUtilsTestGrabWidget"

---

CMakeLists.txt

Fixes https://github.com/commontk/CTK/issues/439

Use "https" instead of "http" if CTK_USE_GIT_PROTOCOL is OFF

---

Libs/Visualization/VTK/Core/vtkDiscretizableColorTransferChart.cpp
Libs/Visualization/VTK/Core/vtkScalarsToColorsContextItem.cpp
Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp

This commit fixes a regression introduced in df055c3 (Introduce limit
range to match both data and LUT ranges)

COMP: ctkVTK[..]Transfer[...]: Support C++98 using CTK_NULLPTR

---

Libs/Visualization/VTK/Widgets/ctkVTKDiscretizableColorTransferWidget.cpp

Fix color widget centering

---

Libs/Visualization/VTK/Widgets/ctkVTKHistogram.cpp

When scalar range is incorrectly set for an image data (e.g., specified incorrectly in the image header)
then out-of-range indexes were computed during histogram computation, which caused memory corruption.
Fixed the problem by adding range check before using the index.

BUG: Fixed memory corruption in histogram computation

---

Libs/Widgets/ctkErrorLogWidget.h

Added Q_INVOKABLE to make it available in python scripting

ENH: add Q_INVOKABLE to ctkErrorLogWidget::SetErrorLogModel

---

Libs/Visualization/VTK/Widgets/ctkVTKChartView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKChartView.h
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsView.cpp
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsView.h
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsWidget.cpp
Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsWidget.h

Fixes both bugs described in https://issues.slicer.org/view.php?id=4526

BUG: Fixed scalars to colors widget range issues

---

CMake/ctkMacroSetupQt.cmake

This reverts commit 2c94808a272545ae199bccf7e2c30d7e75d03c0d.
see https://github.com/commontk/CTK/pull/822

Revert "ENH: Update Qt4 minimum required version to 4.7"

---

Libs/Widgets/ctkDoubleSpinBox.cpp
Libs/Widgets/ctkDoubleSpinBox_p.h

See See https://issues.slicer.org/view.php?id=4633

Fix ctkDoubleSpinBox support for sizeHintPolicy with Qt5

---

Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp

See https://discourse.slicer.org/t/python-interactor-disconnecting/7166
Co-authored-by: Andras Lasso <lasso@queensu.ca>
Co-authored-by: James Butler <jbutler@sonovol.com>

BUG: Update ctkPythonConsole to support auto-completion including unicode characters

---

Libs/DICOM/Core/ctkDICOMDatabase.cpp

I guess it is a right fix, isn't it?

BUG: typo in database, signal not emitted

---

Libs/Widgets/ctkRangeWidget.cpp

see discussion here: https://discourse.slicer.org/t/crash-with-ctkrangewidget/15299/3

Replace Q_ASSERT by qWarning to avoid crash in debug

---

Libs/CommandLineModules/Core/ctkCmdLineModuleReference.h
Libs/Core/ctkUtils.h
Libs/PluginFramework/ctkServiceReference.h
Libs/PluginFramework/ctkServiceRegistration.h
Libs/PluginFramework/service/cm/ctkConfiguration.h
Libs/Widgets/ctkWidgetsUtils.h

<s>* [ ] Update commit message with improved justification</s>

COMP: Consistently export global and namespace symbols

---

CMake/ctkMacroCheckExternalProjectDependency.cmake

```
$ git shortlog 0cc99d3..ea920eb --no-merges
Andras Lasso (1):
Add support for EXTERNAL_PROJECT_ADDITIONAL_DIRS
Jean-Christophe Fillion-Robin (13):
ExternalProjectDependency: Remove debug statement inadvertently integrated
Add support for "ExternalProject_Add_Dependencies"
ExternalProject_SetIfNotDefined: Add test checking interaction with cache variable
ExternalProject_SetIfNotDefined: If any, display corresponding cache value
ExternalProject_SetIfNotDefined: Update docstring
ExternalProject_Include_Dependencies: Check if superbuild variable is improperly set
ExternalProjectDependency: Fix spellcheck
ExternalProjectDependency: Fix variable type of automatically propagated options
circleci: Use dockbuild/centos7-devtoolset7-gcc7 instead of dockbuild/centos6 …
```

ENH: Update ExternalProjectDependency system based on commontk/Artichoke@ea920eb

---

Libs/Visualization/VTK/Widgets/ctkVTKWidgetsUtils.cpp

Bytes per line must be specified to make sure the image is always converted correctly.
The problem was reported and solution was proposed here: https://discourse.slicer.org/t/ctk-vtkimagedatatoqimage-generates-weird-results/25881/2

BUG: Fix ctk::vtkImageDataToQImage function

---

Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRadiotherapySeriesDescriptionRule.cpp
Libs/DICOM/Core/ctkDICOMDisplayedFieldGeneratorRadiotherapySeriesDescriptionRule.h
Libs/DICOM/Core/ctkDICOMIndexer.cpp
Libs/DICOM/Core/ctkDICOMItem.cpp
Libs/DICOM/Core/ctkDICOMItem.h
Libs/DICOM/Core/ctkDICOMModel.cpp
Libs/DICOM/Core/ctkDICOMQuery.cpp
Libs/DICOM/Core/ctkDICOMRetrieve.cpp
Libs/DICOM/Widgets/ctkDICOMAppWidget.cpp
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMObjectModel.cpp
Libs/DICOM/Widgets/ctkDICOMQueryRetrieveWidget.cpp
Libs/DICOM/Widgets/ctkDICOMThumbnailListWidget.cpp

see Slicer/SlicerLanguagePacks#17
see Slicer/SlicerLanguagePacks#12

BUG: Mark translatable strings in Libs/DICOM

---

CMake/ctkWrapPythonQt.py

This commit reverts e51d3b7ee (COMP: Update ctkWrapPythonQt script to consider CTK_NULLPTR)

STYLE: Simplify ctkWrapPythonQt script removing use of obsolete CTK_NULLPTR

---

Libs/DICOM/Widgets/CMakeLists.txt
Libs/DICOM/Widgets/ctkDICOMBrowser.cpp
Libs/DICOM/Widgets/ctkDICOMMetadataDialog.cpp
Libs/DICOM/Widgets/ctkDICOMMetadataDialog.h
Libs/DICOM/Widgets/ctkDICOMVisualBrowserWidget.cpp

@hjmjohnson @pieper @jcfr @lassoan, this PR:
1) Create a dedicated class
2) Set the dialog as non-modal
Ref: 
* https://github.com/commontk/CTK/issues/1251  
* https://github.com/commontk/CTK/pull/1244

Create ctk dicom metadata dialog class
